### ISSUE TITLE
Uncaught UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 21: ordinal not in range(128)


### ISSUE THREAD

**Issue by peter-shr** [tomchadwin/qgis2web#454] opened 2017-03-27 08:24 UTC
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/Users/USER/.qgis2/python/plugins\qgis2web\maindialog.py", line 335, in saveMap
    result = self.exporter.postProcess(results, feedback=self.feedback)
  File "C:/Users/USER/.qgis2/python/plugins\qgis2web\exporter.py", line 142, in postProcess
    feedback.setCompleted('Exported to {}'.format(self.folder))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 21: ordinal not in range(128)

```
qgis2web 2.13.0, QGIS 2.18.5 on Windows 10

**Comment by tomchadwin** [comment] 2017-03-27 08:38
Looks like an internationalization problem. If you are happy editing the code to test this out, can you try doing the following:

1. Open the plugin folder (in .qgis2/python/plugins)
2. Open exporter.py in a text editor
3. Change line 142 from:

```
feedback.setCompleted('Exported to {}'.format(self.folder))
```

to:

```
feedback.setCompleted(u'Exported to {}'.format(self.folder))
```

Make sure you don't change the indent. Save the file, and restart QGIS.

Let us know if that works.

**Comment by philipjohnbarlow** [comment] 2017-03-27 14:51
Hey Tom,

There seems to be a similar issue with custom templates.

![image](https://cloud.githubusercontent.com/assets/14541141/24362576/1ed7216a-1305-11e7-8e51-33fdc67d4ba0.png)

**Comment by tomchadwin** [comment] 2017-03-27 19:18
Can you try editing that line to:

```
s = s.replace (unicode(name), value)
```

**Comment by philipjohnbarlow** [comment] 2017-03-28 07:37
Here we go:

`Error

qgis2web produced an error:

Traceback (most recent call last):
File "C:/Users/philipb/.qgis2/python/plugins\qgis2web\maindialog.py", line 313, in previewMap
preview_file = self.createPreview()
File "C:/Users/philipb/.qgis2/python/plugins\qgis2web\maindialog.py", line 275, in createPreview
dest_folder=utils.tempFolder()).index_file
File "C:/Users/philipb/.qgis2/python/plugins\qgis2web\olwriter.py", line 86, in write
folder=dest_folder)
File "C:/Users/philipb/.qgis2/python/plugins\qgis2web\olwriter.py", line 277, in writeOL
htmlTemplate + ".html", values)
File "C:/Users/philipb/.qgis2/python/plugins\qgis2web\utils.py", line 516, in replaceInTemplate
s = s.replace (unicode(name), value)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1693: ordinal not in range(128)`

**Comment by tomchadwin** [comment] 2017-03-28 08:48
Any ideas which value had a non-ASCII character in it? I need to recreate the issue to solve it. Or you can upload your project and layers.

**Comment by philipjohnbarlow** [comment] 2017-03-28 09:01
It must be my custom template because if I delete it from the templates folder I no longer get the error. 

`<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="initial-scale=1,user-scalable=no,maximum-scale=1,width=device-width">
        <meta name="mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-capable" content="yes">
        @CSSADDRESS@
        @EXTRACSS@
        @LEAFLET_CLUSTERCSS@
        @LEAFLET_LAYERSEARCHCSS@
        @LEAFLET_ADDRESSCSS@
        @LEAFLET_MEASURECSS@
        @OL3_BACKGROUNDCOLOR@
        @OL3_GEOCODINGLINKS@
        @OL3_MEASURESTYLE@
        <style>
        html, body, #map {
            width: 100%;
            height: 100%;
            padding: 0;
            margin: 0;
        }
        </style>
        <title>@PAGETITLE@</title>
    </head>
    <body>
        <div id="map" style="z-index:1;">
            @OL3_POPUP@
        </div>
        @EXP_JS@
        @OL3_PROJ4@
        @OL3_PROJDEF@
        @JSADDRESS@
        @LEAFLET_EXTRAJS@
        @LEAFLET_ADDRESSJS@
        @LEAFLET_MEASUREJS@
        @LEAFLET_CRSJS@
        @OL3_LAYERSWITCHER@
        @OL3_GEOCODINGJS@
        @LEAFLET_CLUSTERJS@
        @LEAFLET_LAYERSEARCHJS@
        @OL3_GEOJSONVARS@
        @OL3_STYLEVARS@
        @OL3_LAYERS@ 
        @QGIS2WEBJS@
        @OL3_WFSVARS@
         <div id="logo">
            <img src="http://cms6.pcnpa.org.uk/Files/files/Mapping/ConsMapImages/pcnp_logo.png" width="300px" alt="some_text" style="position:fixed;bottom:5px;left:5px;z-index:2;">
        </div>
		<div style="position: fixed; Right: 5px; bottom: 20px; background-color: white; opacity:0.6; padding:0px;z-index:2;">
		<p><small><i>© Hawlfraint y Goron a hawliau cronfa ddata Arolwg Ordnans / © Crown copyright and database rights Ordnance Survey 100022534 (2017)</i></small></p>
		</div>
    </body>
</html>`

**Comment by philipjohnbarlow** [comment] 2017-03-28 09:03
This was working in the previous version of the plugin though...

**Comment by tomchadwin** [comment] 2017-03-28 14:09
With the same data? Very odd. OK, can you insert another line into the code, immediately before the line which causes the error. Make sure you match the indentation (use spaces, not tabs):

```python
print(name, value)
```

Restart QGIS (or reload qgis2web, if you have Plugin reloader installed), *open the QGIS Python console*, and start qgis2web. See which is the last name/value pair printed to the console. We can then determine where they came from, and debug from there.

**Comment by tomchadwin** [comment] 2017-03-28 19:00
A guess is that the issue is caused by your QGIS project title. Could that have non-ASCII characters in it?

**Comment by philipjohnbarlow** [comment] 2017-03-29 13:23
There was an indentation error with "s = s.replace (unicode(name), value)", my bad!  I've sorted that but I still get the same error message when I try and use that template.  The template is pretty much a straight copy and paste of the fullscreen one with a couple of div groups and a z-indexes.  I can add these things to the output and it works fine so it's not a huge problem.

**Comment by philipjohnbarlow** [comment] 2017-03-29 13:23
Oh and the project had no name.

**Comment by tomchadwin** [comment] 2017-04-01 09:16
Can you do the `print(name, value)` thing I mentioned above?

**Comment by tomchadwin** [comment] 2017-04-13 16:29
Possibly fixed in master - please test.

**Closed by tomchadwin** 2017-04-13 16:29 UTC
