### ISSUE TITLE
QGIS 2.14.1 (Essen) crashes when loading up qgis2web on Ubuntu 14.04.2 LTS

### ISSUE THREAD

**Issue by tph018** [tomchadwin/qgis2web#236] opened 2016-03-31 17:04 UTC
Hi,

When I attempt to load up qgis2web on QGIS 2.14.1 (Essen) running on Ubuntu 14.04.2 LTS, QGIS automatically crashes. This happens even though I freshly load up QGIS with no underlying project data or spatial data and proceed to load up qgis2web thereafter.

Note, this same QGIS crashing upon loading up qgis2web issue had been occurring on QGIS 2.10 (Pisa) running on Ubuntu 14.04.2 LTS so I thought I'd attempt to upgrade QGIS from version 2.10 (Pisa) to 2.14.1 (Essen). However, it appears that I get the same outcome.

I am using the latest version of qgis2web, 1.5.0.

Is there a way to gather some type of log file to determine the cause of the crash?

Thanks!

**Comment by tomchadwin** [comment] 2016-04-01 11:12
Has anyone else had this problem? I'm on Windows, so I can't recreate, and I don't know how to debug Linux crashes, I'm afraid.

**Comment by luipir** [comment] 2016-04-01 11:56
no minidump created?

btw... first test is to run the plugin in an isolated way => remove all plugins  (or remove/rename .qgis2 folder in your home)... and install only the qgis2web... then check again

**Comment by tph018** [comment] 2016-04-01 17:32
Does QGIS running on Ubuntu generate minidumps when it crashes?

I am at a lost. 

I have tried to remove all QGIS plugins and simply install the lone qgis2web plugin and still get the crash.

I have removed QGIS and re-installed QGIS as follows within a terminal session:
1.sudo apt-get autoremove qgis
2. sudo apt-get --purge remove qgis
3. remove the ~/.qgis2 folder and the ~/.config/QGIS folder
4. sudo apt-get install qgis python-qgis qgis-plugin-grass

I then proceed to launch QGIS 2.14.1 (Essen), install the qgis2web plugin, and then select on the QGIS menu: Web -> qgis2web -> Create web map. The qgis2web window opens for less than a split-second before both the qgis2web window AND the QGIS application crash. Mind you, this crash occurs when there is no specific spatial data being loaded.

The only other consideration to note is that I do have QGIS Server and QGIS Web Client installed on this Ubuntu server and have not removed them. 

Any other suggestions?

**Comment by tomchadwin** [comment] 2016-04-01 19:07
With a clean install, but with some data loaded, does the crash still happen?

**Comment by tph018** [comment] 2016-04-01 19:40
Hi Tom,

Yes, with a clean install but with basic spatial data loaded (in this case, a simple boundary file from a postgis database), QGIS still crashes the moment I choose to open up qgis2web.

On other servers that I work on (using Ubuntu OS or Mac OS), both QGIS and qgis2web work fine without the issues that I experience on this particular Ubuntu 14.04.2 LTS server.

**Comment by tomchadwin** [comment] 2016-04-02 10:20
I think you'll have to find the dump file. Where is it dumped,  @luipir? I wonder if something in QSettings is causing the crash.

**Comment by luipir** [comment] 2016-04-04 09:50
@tph018 is tight... minidump es algo solo de windows. I think is out of scope of this issue to explain how to debug under linux or remote debug python plugins. All the informations are available on the web or qgis.stackexchange.com and it's really hard to be synthetic.

the simplest way to have a rough idea where there could be a crash is to run qgis under gdb doing

gdb <qgis executable>
gdb> r (r means run)
generate the crash then
gdb> where
you'll have a last running stack (probably without source code and debugging symbols in your context)

**Comment by tomchadwin** [comment] 2016-04-11 11:23
Thanks for the help, @luipir. I understand what you say that a crash is out of scope, but since qgis2web seems to cause it, I'm not sure I agree. @tph018, can you follow @luipir's instructions and see if that gives us any more info?

**Comment by luipir** [comment] 2016-04-11 12:49
@tomchadwin crash is not out of scope... explaining how to debug is out of scope, because it's a common debug procedure that can be found on the web.

**Comment by tomchadwin** [comment] 2016-04-11 13:09
Understood. Can you make any progress, @tph018?

**Comment by tph018** [comment] 2016-04-11 13:28
@tomchadwin, 

Let me look into this and see how I may generate further details in the upcoming days before reverting back... For now, I have been working around this crash issue by using qgis2web on another server altogether.

**Comment by mayureshbhole** [comment] 2016-05-03 05:40
i have also same issue in windows when qgis2web run shutdown my entire system

**Comment by tomchadwin** [comment] 2016-05-03 09:26
@mayureshbhole Please can you open a new issue for that? This one relates to a crash on Ubuntu. If you can give more details on your new issue, it will give us a chance to investigate.

**Comment by tomchadwin** [comment] 2016-05-03 09:27
@tph018 I'm going to close this for now through lack of feedback. Please do reopen if you experience this again and if you can provide further details, especially steps to reproduce.

**Closed by tomchadwin** 2016-05-03 09:27 UTC
