### ISSUE TITLE
WFS Default to "encode to JSON" (question)

### ISSUE THREAD

**Issue by philipjohnbarlow** [tomchadwin/qgis2web#118] opened 2015-09-22 14:34 UTC
Hi Tom, from the looks of the settings the plugin defaults to converting WFS layers to JSON?  I put a couple reasonably large WFS layer in (all the stat nature designations in Pembs - 125 polygons) and it took a very long time to load the preview and through up a script error message, probably because of encoding the layer to JSON first?  Might it be better if encode to JSON was default "off" for WFS?

Phil

**Comment by tomchadwin** [comment] 2015-09-22 14:42
I'm not convinced that would be the cause. If you had encode to JSON unchecked, it would still have to download the layers to display them. A different setting to look for is Data export/Mapping library location. Select Local, and see if that speeds things up.

As for whether encode to JSON should be the default or not, I'm not sure. What do other people think?

**Comment by philipjohnbarlow** [comment] 2015-09-22 15:05
I think you might be right, I think there is another reason.  I'd have to test it a bit more but I wonder if there is a feature limit? I put some smaller WFS data sets in and there was no lag and no error message asking me if I wanted to stop the script.

**Comment by tomchadwin** [comment] 2015-09-22 15:12
You could try dropping the Precision setting as a coarse way of simplifying the geometry. It might prove that that is the cause, even if it's not a good solution.

**Comment by tomchadwin** [comment] 2015-09-22 17:19
Closing for now. Re-open if you discover another cause of major lag.

**Closed by tomchadwin** 2015-09-22 17:19 UTC
Labels: question
