### ISSUE TITLE
Python error in Exporting heatmap in leaflet

### ISSUE THREAD

**Issue by kgorro** [tomchadwin/qgis2web#876] opened 2020-05-09 09:54 UTC
Exporting a heatmap to web map using qgis2web, please refer to the stack trace below:
I am using QGIS 3.10 version.

An error has occurred while executing Python code: 

TypeError: %d format: a number is required, not NoneType 
Traceback (most recent call last):
  File "C:/Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 337, in previewMap
    preview_file = self.createPreview()
  File "C:/Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 300, in createPreview
    dest_folder=utils.tempFolder()).index_file
  File "C:/Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 101, in write
    folder=dest_folder)
  File "C:/Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 272, in writeLeaflet
    useVT, useShapes, useOSMB)
  File "C:/Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletLayerScripts.py", line 91, in writeVectorLayer
    feedback)
  File "C:/Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletLayerScripts.py", line 474, in heatmapLayer
    "hmRamp": hmRamp, "hmRadius": hmRadius}
TypeError: %d format: a number is required, not NoneType

**Comment by tomchadwin** [comment] 2020-05-11 08:12
I think this is a duplicate of https://github.com/tomchadwin/qgis2web/issues/871. Try ensuring that the "Weight" field is numeric.

**Closed by tomchadwin** 2020-05-11 08:12 UTC

**Comment by kgorro** [comment] 2020-05-11 09:27
@tomchadwin it is fix now but the heatmap is not showing if I am checking the option "Match Project CRS".

**Comment by tomchadwin** [comment] 2020-05-11 09:57
Leaflet cannot reproject rasters client-side, and OSM is only available from normal tileservers in EPSG:3857. I don't know about what happens with heatmaps in other CRSes, I'm afraid.

**Comment by kgorro** [comment] 2020-05-11 10:13
I am using ESPG:4326 and the heatmap is not showing for this CRS. Can you advise for a workaround? for us show to render heatmap to web?

**Comment by tomchadwin** [comment] 2020-05-11 10:17
Please do follow the guidelines for issues here. You can find the guidelines in the qgis2web Help tab and at https://github.com/tomchadwin/qgis2web/blob/master/README.md#reporting-bugs, and they appear in the text box when you open a new issue.

Specifically, please report any errors, whether Python or Javascript, and please upload your project and layer files. It's nigh-on impossible to debug issues without the information these steps provide.
