### ISSUE TITLE
AttributeError preventing completion

### ISSUE THREAD

**Issue by asitemade4u** [tomchadwin/qgis2web#638] opened 2018-04-17 13:26 UTC
Hi @tomchadwin , thanks for the plugin I could just install on QGis v 3.01 on Ubuntu 16.04 LTS.
I am trying to create a Web map from a fairly simple map and I get this error that stops the whole process:
```
2018-04-17T09:21:07	WARNING	Traceback (most recent call last):
			  File "/home/stsinc/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/qgis2web.py", line 60, in run
			    self.dlg = MainDialog(self.iface)
			  File "/home/stsinc/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 132, in __init__
			    self.populate_layers_and_groups(self)
			  File "/home/stsinc/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 349, in populate_layers_and_groups
			    testDump = layer.renderer().dump()
			AttributeError: 'NoneType' object has no attribute 'dump'
```
The map has only one layer. I attach it as a PDF and I am happy to send it in any other form you want.
Thanks.

![us map](https://user-images.githubusercontent.com/11460106/38872503-689aa956-4221-11e8-957c-f888600bcbcb.png)

**Comment by tomchadwin** [comment] 2018-04-17 14:30
Duplicate of #628. This is now fixed in master, and I've just released 3.0.1 and uploaded it to the plugins repo - can you try upgrading and see if that fixes the problem?

**Closed by tomchadwin** 2018-04-17 14:30 UTC
