### ISSUE TITLE
qgis2web Error with "add layer list" 

### ISSUE THREAD

**Issue by schaeferlea** [tomchadwin/qgis2web#727] opened 2019-03-13 08:28 UTC
Since the latest update qgis2web  doesn't work anymore when I will "add layer list".

**Comment by tomchadwin** [comment] 2019-03-13 09:36
We need a little more description than "doesn't work anymore". What happens? If it's a blank screen in the preview window/exported map in the browser, we need to know if there are any error messages in the console. [Find instructions here](https://github.com/tomchadwin/qgis2web#reporting-bugs). I've just tested with the airports test layer, and it's working for me. If you have multiple layers in your project, can you try removing some layers to see if one layer is causing the problem?

**Comment by schaeferlea** [comment] 2019-03-13 11:06
What happens is: a white screen in the preview and in the exported map. There is no error message or else. Everything is working but the map is just white. As far as I can see, the export-files do look fine. This problem only appears with "add layer list"; without a layer everything works perfectly fine as usual.

**Comment by tomchadwin** [comment] 2019-03-13 11:18
Please follow the instructions in the link in my reply. Specifically, either in qgis2web or your exported map in a browser, press F12, and click on the `Console` tab to find any errors which you can then paste here.

**Comment by schaeferlea** [comment] 2019-03-13 12:03
The `Console` is great; I just found, that the error only appears with layer with multible "items" and I have the impression that the error is in my data…but I can't find it (also: I've exported this data successful in an older version last year).

[The export files
![Bildschirmfoto 2019-03-13 um 12 57 45](https://user-images.githubusercontent.com/8544800/54277496-524e9680-4590-11e9-9907-9485d9afe8b9.png)
![Bildschirmfoto 2019-03-13 um 12 57 33](https://user-images.githubusercontent.com/8544800/54277497-524e9680-4590-11e9-8b97-c116f125780f.png)
![Bildschirmfoto 2019-03-13 um 12 57 07](https://user-images.githubusercontent.com/8544800/54277499-524e9680-4590-11e9-9d6c-4d000a76711f.png)
![Bildschirmfoto 2019-03-13 um 12 57 00](https://user-images.githubusercontent.com/8544800/54277500-524e9680-4590-11e9-8db1-183a110067c0.png)



](https://www.dropbox.com/s/qrj9ohs7lv62m1o/qgis2web_2019_03_13-12_04_48_310157.zip?dl=0)

**Comment by tomchadwin** [comment] 2019-03-13 12:09
Is there an apostrophe in the name of the layer which causes the problem? I wonder if the plugin is failing to handle that?

**Comment by schaeferlea** [comment] 2019-03-13 12:17
Thats it! I have brackets in the layers name! THANK YOU!

**Comment by tomchadwin** [comment] 2019-03-13 12:23
Ah, OK. parentheses `()`, brackets `[]` or braces `{}`? You shouldn't have to avoid them, so this is a bug I need to fix.

**Comment by schaeferlea** [comment] 2019-03-13 12:25
parentheses ()

**Comment by tomchadwin** [comment] 2019-03-13 12:25
Got it - I'll investigate. Thanks for investigating and reporting back.

**Comment by schaeferlea** [comment] 2019-03-13 12:27
Thank you for this nice plugin!

**Comment by tomchadwin** [comment] 2019-03-13 12:28
Hrm. It works with parentheses for me. Were there any other special characters in the layer name which could have been the cause?

**Comment by tomchadwin** [comment] 2019-03-13 12:28
A simpler question: what was your layer name when it was failing?

**Comment by schaeferlea** [comment] 2019-03-13 12:35
That is odd! now it works for me with parentheses too. The layer name was fine, the parentheses were in the name of the subitems. It was just something like "have (232)"

**Comment by schaeferlea** [comment] 2019-03-13 12:38
I used the ⊂ symbol too; but that doesn't seem to be problematic. With other layer using paretheses, I still get the white-screen. I have to delete every parethese, loading the preview successfully and then I can add paretheses again. strange.

**Comment by tomchadwin** [comment] 2019-03-13 12:40
Very odd. Just to check, the problematic parentheses were manually typed as part of the layer name/filename, and not automatically generated by QGIS appending the feature count?

**Comment by schaeferlea** [comment] 2019-03-13 12:41
![Bildschirmfoto 2019-03-13 um 13 41 04](https://user-images.githubusercontent.com/8544800/54279569-aa3bcc00-4595-11e9-98a4-697c0dc7db9b.png)

**Comment by tomchadwin** [comment] 2019-03-13 12:41
Ah, it's a categorized layer? OK, let me test that.

**Comment by schaeferlea** [comment] 2019-03-13 12:41
not automatically generated .

**Comment by tomchadwin** [comment] 2019-03-13 12:44
I'm really struggling to recreate the error. I've added parentheses into the label for a category, but it still works. Many apologies!

**Comment by schaeferlea** [comment] 2019-03-13 13:43
I begin to think that there must be something in my data that causes trouble…

**Comment by tomchadwin** [comment] 2019-03-14 11:35
I wish I could help, but I guess I'll close this issue for now. Comment again if you have more info.

**Closed by tomchadwin** 2019-03-14 11:35 UTC
