### ISSUE TITLE
"Highlight features" breaks "Show popups on hover" in OL3

### ISSUE THREAD

**Issue by marcobra** [tomchadwin/qgis2web#100] opened 2015-08-18 14:45 UTC
hi Tom

Installed version: 0.21.4

ol3 (preview and export) do not show popup on elements...

Thank 
Marco

**Comment by tomchadwin** [comment] 2015-09-07 09:18
@marcobra It's working for me at the moment. Have you changed the dropdown for your layer which enables popups ("Info popup content")?

**Comment by marcobra** [comment] 2015-09-16 10:37
yes,  now  plugin is in rel. 0.23.0

![nopop](https://cloud.githubusercontent.com/assets/1607387/9902532/77616910-5c6f-11e5-97c5-8cf1cc87e8c8.png)

**Comment by tomchadwin** [comment] 2015-09-18 09:27
I still can't recreate this - the popups work for me. Can you send me your layer?

**Comment by tomchadwin** [comment] 2015-09-18 13:25
Thanks for the layer. It works for me, with my current settings. I'll try to match yours and see what happens.

**Comment by tomchadwin** [comment] 2015-09-18 13:28
Ah. The problem is "Show popups on hover". Uncheck that, and it works. SO I need to fix that option, or remove it.

**Comment by tomchadwin** [comment] 2015-09-18 14:46
It looks as though the highlight code is failing, and causing the hover popup code to fail along with it.

**Comment by tomchadwin** [comment] 2015-09-18 14:46
Yes. Try turning off "Highlight features" and see if the hovering popups return.

**Comment by tomchadwin** [comment] 2015-09-18 15:21
Does anyone still have a copy of @volaya's "Export to Openlayers 3" (qgis-ol3) plugin? If so, can you test "Highlight features"? If features do not highlight, can you see if there are any JS console errors?

**Comment by boesiii** [comment] 2015-09-18 15:47
I tested it and "Highlight Features" and "Show Popups on Hover" work as expected.

**Comment by tomchadwin** [comment] 2015-09-18 15:48
Thanks, @boesiii. Can you send me a copy of the whole plugin? @volaya deleted it and its GH repo.

**Comment by boesiii** [comment] 2015-09-18 16:28
It looks like the original highlight code has changed.  It worked if I made the following changes to index.html  

Modify Line 159 in index.html
 featureOverlay.getSource().removeFeature(highlight);

Modify Line 162 in index.html
featureOverlay.getSource().addFeature(currentFeature);

**Comment by tomchadwin** [comment] 2015-09-18 17:33
Regression introduced with https://github.com/tomchadwin/qgis2web/commit/9edb90ba9c80dabc66c5247644b48b0e07e83747. Apologies. Will patch on Monday. Thanks for the help, @boesiii.

**Comment by marcobra** [comment] 2015-09-21 07:49
Tom, 
 turning off "Highlight features" and the hovering popups return.

Modifing the ~/.qgis2/python/plugins/qgis2web/templates/basic.html
to generate @boesiii suggestion made all works

Marco

**Comment by tomchadwin** [comment] 2015-09-21 08:46
Fixed in master - can you test?

**Comment by marcobra** [comment] 2015-09-21 08:58
tested from master is ok now preview and generate code

**Comment by tomchadwin** [comment] 2015-09-21 08:59
Great. I'll release and push to the QGIS plugin repo as soon as I can. Thanks @marcobra and @boesiii for tracking this one down.

**Closed by tomchadwin** 2015-09-21 08:59 UTC

**Comment by tomchadwin** [comment] 2015-09-29 09:04
Released as 0.24.0 and pushed to QGIS plugins repo

**Comment by kannes** [comment] 2019-10-22 12:10
This is happening for me in qgis2web 3.7.0 on 3.8.3-Zanzibar with a simple line layer. "Show popups on hover" works until I also enable "highlight on hover".
