### ISSUE TITLE
qgis2web does not work under W10 and QGIS 2.12 -16

### ISSUE THREAD

**Issue by peter-shr** [tomchadwin/qgis2web#322] opened 2016-08-19 10:30 UTC
qgis2web 1.13.1, Windows 10, for QGIS 2.12, 2.14, 2.16
Neither OpenLayers or Leaflet Web maps are created.
Output data are shapefiles.
When clicking on 'Update preview'
**Error**
qgis2web produced an error:
Traceback (most recent call last):
File "C:/Users/..../.qgis2/python/plugins\qgis2web\maindialog.py", line 134, in previewMap
MainDialog.previewLeaflet(self)
File "C:/Users/..../.qgis2/python/plugins\qgis2web\maindialog.py", line 308, in previewLeaflet
visible, cluster, json, params, popup)
File "C:/Users/..../.qgis2/python/plugins\qgis2web\leafletWriter.py", line 91, in writeLeaflet
layerFileName, safeLayerName, minify, canvas)
File "C:/Users/..../.qgis2/python/plugins\qgis2web\leafletLayerScripts.py", line 17, in exportJSONLayer
cleanedLayer = writeTmpLayer(i, eachPopup)
File "C:/Users/..../.qgis2/python/plugins\qgis2web\utils.py", line 93, in writeTmpLayer
outFeat.setGeometry(feature.geometry())
TypeError: QgsFeature.setGeometry(QgsGeometry): argument 1 has unexpected type 'NoneType'

When clicking on 'Export'
TypeError: QgsFeature.setGeometry(QgsGeometry): argument 1 has unexpected type 'NoneType' 
Traceback (most recent call last):
  File "C:/Users/..../.qgis2/python/plugins\qgis2web\maindialog.py", line 150, in saveMap
    MainDialog.saveLeaf(self)
  File "C:/Users/..../.qgis2/python/plugins\qgis2web\maindialog.py", line 330, in saveLeaf
    cluster, json, params, popup)
  File "C:/Users/..../.qgis2/python/plugins\qgis2web\leafletWriter.py", line 91, in writeLeaflet
    layerFileName, safeLayerName, minify, canvas)
  File "C:/Users/..../.qgis2/python/plugins\qgis2web\leafletLayerScripts.py", line 17, in exportJSONLayer
    cleanedLayer = writeTmpLayer(i, eachPopup)
  File "C:/Users/..../.qgis2/python/plugins\qgis2web\utils.py", line 93, in writeTmpLayer
    outFeat.setGeometry(feature.geometry())
TypeError: QgsFeature.setGeometry(QgsGeometry): argument 1 has unexpected type 'NoneType'

Python-Version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS-Version: 2.16.1-Nødebo Nødebo, 8545b3b

**Comment by tomchadwin** [comment] 2016-08-19 10:38
Duplicate of https://github.com/tomchadwin/qgis2web/issues/274.

**Closed by tomchadwin** 2016-08-19 10:38 UTC

**Comment by peter-shr** [comment] 2016-08-19 11:08
Sorry, my search was probably not intense enough.
Will it then try and create geometryen.
Peter
 

    Tom Chadwin <notifications@github.com> schrieb am 12:38 Freitag, 19.August 2016:
 

 Duplicate of #274.—

**Comment by tomchadwin** [comment] 2016-08-19 12:29
Fix committed to master. Please test.

**Comment by peter-shr** [comment] 2016-08-30 07:25
Hello,
Was until now replies, version 1.14.0 works fine.
regards Peter
