### ISSUE TITLE
reprojecting goes wrong

### ISSUE THREAD

**Issue by riccardoklinger** [tomchadwin/qgis2web#74] opened 2015-06-29 10:25 UTC
I was exporting a very "simple" project with the plugin and simply choose to display on field. no extra selections were made. clicked on export and all my regular point grid was on one line. the points are in EPSG 32632. reprojection and using basemap does not work! check this video:
http://www.digital-geography.com/wp-content/uploads/2015/06/qgis2web_issue.mp4

**Comment by tomchadwin** [comment] 2015-06-29 10:26
Leaflet or OL3?

**Comment by riccardoklinger** [comment] 2015-06-29 10:26
both are not working. download the vid.

**Comment by tomchadwin** [comment] 2015-06-29 10:29
Basemaps will not work in other projections if the providers' tileservers don't serve in that projection, which I guess most or all of them won't. Match CRS has not been enabled for OL3 export yet. That leaves Leaflet as the problem. I'll look into it.

**Comment by riccardoklinger** [comment] 2015-06-29 10:37
But what happens if you not choose "match project crs" in openlayers: I am selecting a basemap and not to use the project crs. no basemap is shown:

http://www.digital-geography.com/wp-content/uploads/2015/06/qgis2webissue2.mp4

**Comment by tomchadwin** [comment] 2015-06-29 10:40
Hmm, this might be an artefact of how settings are saved. In the QGIS Python console, can you do the following:

```python
from PyQt4.QtCore import QSettings
print QSettings().value("qgis2web/Base layer")
```

**Comment by riccardoklinger** [comment] 2015-06-29 10:42
returns "1"

**Comment by tomchadwin** [comment] 2015-06-29 10:45
No, OK, that's right (= OSM Standard).

**Comment by tomchadwin** [comment] 2015-06-29 11:10
I haven't managed to recreate this yet. I've opened layer in 27700 and set the project to 27700 as well. I've not checked Match project CRS, but my layer and basemap show up fine in both OL3 and Leaflet.

Can you send me your layer?

**Comment by riccardoklinger** [comment] 2015-06-29 11:21
here you go: http://www.digital-geography.com/wp-content/uploads/2015/06/windmap.zip

**Comment by tomchadwin** [comment] 2015-06-29 11:27
Interesting. So is the reprojection correct in OL3 (rectangle of points rotated approx. 30 degrees)? As far as you can tell without a basemap, I mean.

**Comment by tomchadwin** [comment] 2015-06-29 11:29
No, wait. The basemap is there - zoom out a long way and you'll see it. It's the reprojection which is wrong (I presume).

**Comment by tomchadwin** [comment] 2015-06-29 11:32
And, in fact, the OL3 reprojection is correct (at least it matches what I see in QGIS with OSM loaded via OpenLayers plugin).

So, the issue is that Leaflet is not reprojecting correctly.

**Comment by tomchadwin** [comment] 2015-06-29 12:11
OL3 exported JSON:

```javascript
"crs":{"type":"name","properties":{"name":"urn:ogc:def:crs:EPSG::3857"}}
```

Leaflet:

```javascript
"crs":{"type":"name","properties":{"name":"urn:ogc:def:crs:OGC:1.3:CRS84"}}
```

So the writeAsVectorFormat calls must differ.

**Comment by tomchadwin** [comment] 2016-01-06 20:02
For 1.0.0beta, I did quite a lot of work on projections. Is this still failing? I'll also test.

**Comment by tomchadwin** [comment] 2016-01-06 23:13
Looks better:

- OL3 ?works (with and without match CRS)
- Leaflet works with Match CRS, but misprojects without match CRS

Do you agree?

**Comment by philipjohnbarlow** [comment] 2016-01-07 08:35
Related to this I am getting the following error in the preview in both OL3 and Leaflet with the Match CRS option when using a BNG (27700) WMS base map. 

![crs](https://cloud.githubusercontent.com/assets/14541141/12165904/945badca-b519-11e5-99cf-8642b545a336.PNG)

**Comment by tomchadwin** [comment] 2016-01-07 09:25
Can you pull down current master and try again?  Thought I fixed that last night. Will test myself soon.

**Comment by philipjohnbarlow** [comment] 2016-01-07 14:47
Just tried it with master and match CRS works fine in both OL3 and Leaflet.

**Comment by lucacasagrande** [comment] 2016-01-29 17:08
Just noticed that with OL3 Rasters don't work if they use a projection other than EPSG:3857

**Comment by tomchadwin** [comment] 2016-01-29 22:48
The projection of the raster itself, or of the project? Or of the output with "Match project CRS"?

**Comment by volcan01010** [comment] 2016-06-16 15:14
After some playing, it seems that OpenLayers can reproject raster on the fly.

+  Add vector in EPSG:27700 and set project CRS to match layer
+  Add raster in EPSG:3857 (e.g. created by saving from OpenLayers plugin)
+  Open qgis2web
    +  In OpenLayers 3: both vector and raster are visible
    +  In Leaflet: only vector layer is visible

**Comment by volcan01010** [comment] 2016-06-16 15:21
### Comparison of with and without _Match project CRS_:

+  Add vector layer in EPSG:27700
+  Export in qgis2web, firstly without then with matching CRS

Diff:

```
tw-johns@qgishack:/tmp/qgis2web/exported$ diff qgis2web_1466090261.7/index.html qgis2web_1466090268.69/index.html 
18a19,20
>         <script src="js/proj4.js"></script>
>         <script src="js/proj4leaflet.js"></script>
32a35,37
>         var crs = new L.Proj.CRS('EPSG:27700', '+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +towgs84=446.448,-125.157,542.06,0.15,0.247,0.842,-20.489 +units=m +no_defs', {
>             resolutions: [2800, 1400, 700, 350, 175, 84, 42, 21, 11.2, 5.6, 2.8, 1.4, 0.7, 0.35, 0.14, 0.07],
>         });
38a44,46
>             crs: crs,
>             continuousWorld: false,
>             worldCopyJump: false, 
46,50d53
<         var basemap0 = L.tileLayer('http://a.tile.stamen.com/terrain/{z}/{x}/{y}.png', {
<             attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>,<a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash;Map data: &copy; <a href="http://openstreetmap.org">OpenStreetMap</a>contributors,<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>',
<             maxZoom: 28
<         });
<         basemap0.addTo(map);
```

**Comment by volcan01010** [comment] 2016-06-16 15:55
I think that this bug is fixed by version 1.9.2 against QGIS 2.14.3.  I 

Project CRS: 27700
3 vector layers, in different projections:  27700, 4326, 3857

+  Open qgis2web, add OSM basemap.
+  Check OpenLayers and Leaflet, with and without "Match project CRS".
+  **Results:** Vector features align correctly in all cases.  Basemapping is not shown in Leaflet with Match project CRS (because Leaflet only supports basemaps in 3857)

**Comment by tomchadwin** [comment] 2016-06-17 11:19
So I can summarize as follows:

#### OL3
- vectors work
- rasters work

#### Leaflet
- vectors work
- rasters fail

Is that right?

**Comment by lucacasagrande** [comment] 2016-06-17 14:41
I think that there is still a problem with raster's style.

**Comment by tomchadwin** [comment] 2016-06-17 14:43
@lucacasagrande Yes, but I've called that a different issue: #148. That issue deals with styling, but do we think that my summary above of reprojection is correct?

**Comment by lucacasagrande** [comment] 2016-06-17 14:46
Yes, you are right. :+1:  I will try to fix that during this weekend.

**Comment by tomchadwin** [comment] 2016-06-17 14:51
Thanks, Luca!

**Comment by tomchadwin** [comment] 2016-07-16 19:50
I'm going to close this, as I believe everything in it is fixed apart from Leaflet rasters. That can have its own issue.

**Closed by tomchadwin** 2016-07-16 19:50 UTC
Labels: bug, Leaflet
