### ISSUE TITLE
Lines not displayed

### ISSUE THREAD

**Issue by pcav** [tomchadwin/qgis2web#384] opened 2017-01-14 07:55 UTC
See attached images. Simple line styling.
![schermata da 2017-01-14 08-53-53](https://cloud.githubusercontent.com/assets/691842/21953435/1e669866-da37-11e6-809e-3c7055ccc453.png)
![schermata da 2017-01-14 08-53-34](https://cloud.githubusercontent.com/assets/691842/21953436/1e669d5c-da37-11e6-9831-07af12c80de0.png)

**Comment by tomchadwin** [comment] 2017-01-14 20:11
Can you describe the symbology in more detail, or upload its .qml?

**Comment by pcav** [comment] 2017-01-15 07:51
qml uploades. However, this does not seem to be dependent on style (it happenas with the rendom style automatically applied on loading 

as well).

**Comment by tomchadwin** [comment] 2017-01-16 10:33
That test layer renders fine for me. Can you screenshot the rest of the window, so I can see your config?

**Comment by pcav** [comment] 2017-01-16 10:41
Which part/configs? Even more strange, now I cannot render even polygons in OL, whereas in Leaflet only polygins are show, as before. It is likely a local issue then.

**Comment by tomchadwin** [comment] 2017-01-16 10:42
> Which part/configs?

The lower-left pane in the qgis2web dialog.

> It is likely a local issue then

Still needs to be solved.

**Comment by pcav** [comment] 2017-01-16 10:43
![schermata da 2017-01-16 11-43-13](https://cloud.githubusercontent.com/assets/691842/21979849/0400b69a-dbe1-11e6-82aa-314fd4d95fb7.png)

**Comment by tomchadwin** [comment] 2017-01-16 11:21
In the preview or export, can you zoom out to see whether the problem is simply the viewport coords? Also, in the exported browser, can you hit F12 and find the console, to check for errors there?

**Comment by tomchadwin** [comment] 2017-01-30 15:25
Closing for now - reopen if still an issue.

**Closed by tomchadwin** 2017-01-30 15:25 UTC
