### ISSUE TITLE
Simple fill opacity ignored

### ISSUE THREAD

**Issue by mixedbredie** [tomchadwin/qgis2web#10] opened 2015-04-23 14:02 UTC
I have two polygon layers in my test project.  They are using simple fill with the fill opacity set to 0% (totally transparent) and border nice and solid.

Exporting to both Leaflet and OL3 ignores the opacity setting and my layers are filled with colour.

**Comment by tomchadwin** [comment] 2015-04-24 13:20
Does this error also occur in qgis2leaf?

**Comment by tomchadwin** [comment] 2015-05-07 17:47
This is because, though we get layer opacity in both OL3 and Leaflet export, and style transparency in Leaflet export, neither gets the alpha of colours of individual style elements yet.

**Comment by pcav** [comment] 2015-05-11 08:40
Same for layers with empty fill, with OL backend.

**Comment by tomchadwin** [comment] 2015-05-15 17:01
I've implemented what I think the fix for this is, only in the Leaflet code. @mixedbredie, can you confirm this addresses the problem in Leaflet?

**Comment by mixedbredie** [comment] 2015-05-20 15:00
Ok, apologies for the delay in getting back to you. I've updated the plugin. I've added a polygon layer, set fill to "no fill", border to solid black 0.4mm and opacity to 0%. Exporting to leaflet adds the layer to the layer switcher control but it is completely transparent on the map.

    function doStylechxcommcouncils(feature) {
			return {
				color: '#000000',
				fillColor: '#b66dc2',
				weight: 2.0,
				dashArray: '0',
				opacity: 0.0,
				fillOpacity: 0.0
			};

Exporting to OL3 with the same QGIS style setting results in the polygon layer added to the layer switcher and is visible on the map with solid colour fill and black outlines. No opacity at all.

    var styleCache_chxcommcouncils={}
                    var style_chxcommcouncils = function(feature, resolution){
                        var value = ""
                        var style = [ new ol.style.Style({
                            stroke: new ol.style.Stroke({color: "rgba(0,0,0,1.0)", lineDash: null, width: 1}), 
                        fill: new ol.style.Fill({color: "rgba(182,109,194,1.0)"})
                        })
                        ];
                        var labelText = "";
                        var key = value + "_" + labelText

                        if (!styleCache_chxcommcouncils[key]){
                            var text = new ol.style.Text({
                                  font: '8.25px Calibri,sans-serif',
                                  text: labelText,
                                  fill: new ol.style.Fill({
                                    color: "rgba(0, 0, 0, 255)"
                                  }),
                                });
                            styleCache_chxcommcouncils[key] = new ol.style.Style({"text": text});
                        }
                        var allStyles = [styleCache_chxcommcouncils[key]];
                        allStyles.push.apply(allStyles, style);
                        return allStyles;
                    };

The QGIS QML style is like this:

        <symbols>
      <symbol alpha="1" type="fill" name="0">
        <layer pass="0" class="SimpleFill" locked="0">
          <prop k="border_width_map_unit_scale" v="0,0"/>
          <prop k="color" v="182,109,194,0"/>
          <prop k="joinstyle" v="bevel"/>
          <prop k="offset" v="0,0"/>
          <prop k="offset_map_unit_scale" v="0,0"/>
          <prop k="offset_unit" v="MM"/>
          <prop k="outline_color" v="0,0,0,255"/>
          <prop k="outline_style" v="solid"/>
          <prop k="outline_width" v="0.4"/>
          <prop k="outline_width_unit" v="MM"/>
          <prop k="style" v="no"/>
        </layer>
      </symbol>
    </symbols>

**Comment by tomchadwin** [comment] 2015-05-27 08:55
To clarify - the Leaflet behaviour is correct, and the OL3 wrong?

**Comment by tomchadwin** [comment] 2015-05-27 08:59
No, scratch that. You mean that in Leaflet, the fill is correctly transparent, but the border is also mistakenly transparent?

**Comment by tomchadwin** [comment] 2015-05-27 09:13
OK, in your description "set fill to "no fill", border to solid black 0.4mm and opacity to 0%", I need to know more precisely to which opacity setting you are referring. Any chance of a screenshot of the style dialogue?

**Comment by tomchadwin** [comment] 2015-06-16 11:31
I've made some changes to master on this *in Leaflet export only*, for simple styles (not categorized or graduated):

- Fill style: "No Brush" should now be observed for polygons
- border opacity should now be correctly separated from fill opacity

I'd appreciate some testing to let me know if this has worked, before I try to replicate the changes over to categorized and graduated styles.

**Comment by boesiii** [comment] 2015-06-16 11:50
After testing, he polygon fill and border have the correct opacity\transparency in my leaflet map but there is a weird issue with the border when polygons share a common side.  When polygon borders share a common line the resulting line looks darker, see image below.


![trans](https://cloud.githubusercontent.com/assets/2079638/8182300/2095d53c-13fc-11e5-8cf8-e132b9ddaec0.PNG)

**Comment by tomchadwin** [comment] 2015-06-16 11:52
That's expected behaviour - two partially opaque lines overlaid make one darker one. Does it not do this in the QGIS GUI?

**Comment by boesiii** [comment] 2015-06-16 12:04
No, it does not do this in Qgis.

**Comment by tomchadwin** [comment] 2015-06-16 12:43
Interesting. However, I can't think of a way around it in Leaflet, I'm afraid.

**Comment by boesiii** [comment] 2015-06-16 13:15
I didn't think there was a fix just wanted to mention it.

**Comment by tomchadwin** [comment] 2015-06-16 13:16
No, but it's frustrating that QGIS can manage it. I don't know how, regardless of technology. Perhaps it eliminates congruent lines before rendering. Ah well.

**Comment by tomchadwin** [comment] 2015-06-16 13:48
Fix replicated to categorized and graduated styles in master

**Comment by boesiii** [comment] 2015-06-16 15:13
I am getting an html error when exporting to leaflet when the vector data is a polyline.  The error is on line 89 in index.html, unexpected token ,

When it is styling the polyline the opacity property does not have a value
opacity: ,

I am guessing it should be
opacity: ' ',

**Comment by tomchadwin** [comment] 2015-06-16 15:20
Can you email me a simple polyline SHP?

**Comment by tomchadwin** [comment] 2015-06-16 15:28
@boesiii I've just tried a fix in master - can you try that?

**Comment by boesiii** [comment] 2015-06-16 15:41
I am getting a python error in Qgis

Traceback (most recent call last):
  File "C:/Users/username/.qgis2/python/plugins\qgis2web\maindialog.py", line 178, in saveLeaf
    outputFile = writeLeaflet(folder, 600, 400, 1, layers, visible, "", cluster, "", "", "", "", labels, "", 0, json, params)
  File "C:/Users/username/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 214, in writeLeaflet
    borderWidth_str = str(symbol.outlineWidth())
AttributeError: 'QgsMarkerSymbolV2' object has no attribute 'outlineWidth'

**Comment by tomchadwin** [comment] 2015-06-16 15:43
Apologies - you've caught me in the middle of developing something else. Let me get it minimally functional and commit.

**Comment by tomchadwin** [comment] 2015-06-16 15:46
OK, try master now?

**Comment by boesiii** [comment] 2015-06-16 16:00
It is working now.

**Comment by tomchadwin** [comment] 2015-06-16 16:29
Great. Thanks for testing.

**Comment by tomchadwin** [comment] 2015-07-16 17:47
Closing as no feedback for some time. Reopen if appropriate.

**Closed by tomchadwin** 2015-07-16 17:47 UTC
Labels: enhancement, Leaflet, OL3, styles
