### ISSUE TITLE
QGIS2Web does not open the dialog settings box

### ISSUE THREAD

**Issue by CvTooren** [tomchadwin/qgis2web#418] opened 2017-02-20 12:01 UTC
QGIS2Web version 2.6.0.
QGISversion 2.18.3.
Windows 10

When I start QGIS2Web by clicking on the button,  the plug-in starts right away, without giving any dialog box in which I can enter my settings. It start immediately executing algorithm, not coming further then 0%. After e.g. 10 minutes my hard disk has no space anymore. Before start it has at least 5Gb.

Regards
Coen van Tooren

**Comment by boesiii** [comment] 2017-02-22 21:33
See issue #419

**Comment by tomchadwin** [comment] 2017-02-28 16:08
Closing as duplicate of #419.

**Closed by tomchadwin** 2017-02-28 16:08 UTC
