### ISSUE TITLE
layers not added in leaflet

### ISSUE THREAD

**Issue by riccardoklinger** [tomchadwin/qgis2web#38] opened 2015-05-06 18:27 UTC
tried new master 0.3:  layers exported in leaflet option (JSONs are in /data) but layer add is not complete. only raster is shown:
preview also does not show any layers
![screenshot from 2015-05-06 20 19 50](https://cloud.githubusercontent.com/assets/7377897/7500392/abf364bc-f42d-11e4-9924-6689ce663fa4.png)
got this error in firebug:
referenceError: exp_placesfew1EPSG3857JSON is not defined
feature_group.addLayer(exp_placesfew1EPSG3857JSON);

it is not added via "new L.geoJson(...) like this 
	var exp_placesfew1JSON = new L.geoJson(exp_placesfew1,{
		onEachFeature: pop_placesfew1,
		pointToLayer: function (feature, latlng) {  
			return L.circleMarker(latlng, {
				radius: 4.0,
				fillColor: '#ff30ee',
				color: '#000000',
				weight: 1,
				opacity: 1.0,
				fillOpacity: 1.0
			})
		}
	});

is it still a problem of projection?

**Comment by tomchadwin** [comment] 2015-05-07 07:34
Isn't that qgis2leaf test data layer the one with the disallowed character in the attribute name? I don't think qgis-ol3 catches those issues. Can you try removing the space and seeing if that exports?

**Comment by tomchadwin** [comment] 2015-05-07 07:41
Confirmed that removing the field with illegal characters in the name allows OL3 export.

**Comment by riccardoklinger** [comment] 2015-05-07 10:01
But I tried the export to leaflet option only..

_______________________________

Geolicious GbR
Agentur für Geo-Kommunikation

Riccardo Klinger
Geschäftsführer

mobil: 0176 63437298
e-mail: riccardo.klinger@geolicious.de
web: www.geolicious.de

Geolicious GbR
c/o Daniel Kerkow
Binzstraße 48
13189 Berlin

Gesellschafter:
Riccardo Klinger
Daniel Kerkow
Jakob Hafner

Sitz der Gesellschaft: Berlin
Ust-ID: DE289107523

**Comment by tomchadwin** [comment] 2015-05-07 10:31
OK, you are right - something is fundamentally wrong in Leaflet export. Can you get any layers to export at all?

**Comment by riccardoklinger** [comment] 2015-05-07 10:32
lazers are exported and valid in the /data folder. but the "new L.geoJSON"
command for leaflet to assign a variable with the geoJSON is missing
sometimes.

_______________________________

Geolicious GbR
Agentur für Geo-Kommunikation

Riccardo Klinger
Geschäftsführer

mobil: 0176 63437298
e-mail: riccardo.klinger@geolicious.de
web: www.geolicious.de

Geolicious GbR
c/o Daniel Kerkow
Binzstraße 48
13189 Berlin

Gesellschafter:
Riccardo Klinger
Daniel Kerkow
Jakob Hafner

Sitz der Gesellschaft: Berlin
Ust-ID: DE289107523

**Comment by tomchadwin** [comment] 2015-05-07 11:23
I've had a long look at this, and this seems to be what I see:

- layers export fine when the plugin is first executed
- layers fail to export if you change dialog settings, and then re-export

Do you see the same? In other words:

- Is the Leaflet export working correctly if you export straight away without changing dialogue settings?
- Does the Leaflet export fail if you change the dialogue settings before export?

**Comment by tomchadwin** [comment] 2015-05-07 13:37
Possibly fixed in master. Underlying issue was that Leaflet export was looping through all QGIS, not just layers selected in plugin UI. Can you test, @riccardoklinger?

**Closed by tomchadwin** 2015-05-07 13:37 UTC
Labels: bug, Leaflet, vectors
