### ISSUE TITLE
Error with features (not layers) with no geometry

### ISSUE THREAD

**Issue by planologie** [tomchadwin/qgis2web#274] opened 2016-05-14 11:19 UTC
On the standalone version of qgis and also on the server I get by export the next message:

Fault - KIO client
The file or directory  /tmp/qgis2web/qgis2web_2016_05_14-13_13_55/index.html does not exist.

Can you help me.

**Comment by tomchadwin** [comment] 2016-05-14 11:40
I'm not sure, to be honest. Can anyone else help? What on earth is KIA client?

What OS are you running on?

To clarify, the plugin is for QGIS desktop, not Server, so don't try it on the latter.

**Comment by planologie** [comment] 2016-05-14 14:39
On my desktop I'm running linux Opensuse Leap 42.1.
On the server I'm running Centos7.

I will use qgis2web for viewing maps on a website.



Op 14-05-16 om 13:40 schreef Tom Chadwin:

**Comment by tomchadwin** [comment] 2016-05-16 09:15
Can you use a file manager to browse to the export folder location - see if the folder is there. If it is, see if `index.html` is in it.

**Comment by planologie** [comment] 2016-05-17 12:18
I think I have found the problem. The problem is the shapefile. With 
other shapefiles I get a index.html.


In the export folder I see a folder layers en resources. The folder 
layer is empty and de folder resources has been filled.

When I use in qgis2web Leaflet instead of OL3 I get next messages.

qgis2web produced an error:

Traceback (most recent call last):
File "/.qgis2/python/plugins/qgis2web/maindialog.py", line 134, in 
previewMap
MainDialog.previewLeaflet(self)
File "/.qgis2/python/plugins/qgis2web/maindialog.py", line 307, in 
previewLeaflet
visible, cluster, json, params, popup)
File "/.qgis2/python/plugins/qgis2web/leafletWriter.py", line 95, in 
writeLeaflet
layerFileName, safeLayerName, minify, canvas)
File "/.qgis2/python/plugins/qgis2web/leafletLayerScripts.py", line 15, 
in exportJSONLayer
cleanedLayer = writeTmpLayer(i, eachPopup)
File "/.qgis2/python/plugins/qgis2web/utils.py", line 90, in writeTmpLayer
outFeat.setGeometry(feature.geometry())
TypeError: QgsFeature.setGeometry(QgsGeometry): argument 1 has 
unexpected type 'NoneType'







Op 16-05-16 om 11:15 schreef Tom Chadwin:

**Comment by planologie** [comment] 2016-05-23 11:36
Now I know what is wrong.
Some records don't have a geometry.
When I delete this records. I get the index.html.
Is it possible to check the geometry in qgis2web, with returning a 
message "wrong geometry"?
Thank you for your help.




Op 16-05-16 om 11:15 schreef Tom Chadwin:

**Comment by tomchadwin** [comment] 2016-05-24 08:29
OK, I see the problem. The plugin avoids layers with no geometry, but does not check individual features to make sure they have geometry. I'll look into it.

**Comment by curtains23** [comment] 2016-08-01 14:00
I have the same problem, is it resolved?

**Comment by tomchadwin** [comment] 2016-08-16 09:41
Not resolved yet, no. Can you confirm that the issue is specifically when you have a layer in which some features have geometry, and some do not?

**Comment by curtains23** [comment] 2016-08-16 09:46
Yes! Some lack geometry.

Den tis 16 aug. 2016 11:42Tom Chadwin <notifications@github.com> skrev:

**Comment by tomchadwin** [comment] 2016-08-19 12:28
Fix committed to master. Please test.

**Closed by tomchadwin** 2016-08-19 12:28 UTC
Labels: bug, Leaflet, OL3, vectors

**Comment by tomchadwin** [comment] 2016-08-23 15:12
Released as 1.14.0 and pushed to QGIS plugins repo.
