### ISSUE TITLE
small visual improvement

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [tomchadwin/qgis2web#676] opened 2018-09-06 14:22 UTC
Hi Tom,

The Leaflet maps (qgis 2.18.20, qgis2web 2.34.0) come with standard links the leafletjs.com and your github site. The line however always end with a comma, which to me seems unnecessary.

I personally add source information (to acknowledge the source of the used data) after the two links, and I do this by editing the index.html file, adding it behind the reference to the github site. So I end up with this comma somewhere in between the links and text.

The comma is coded in the leaflet.js file in the map JS (search for "t.join" in the file). Is it possible to remove this comma (but keep the "single space" in future updates? It saves me from editing this single file on every webmap.

Thank you.

**Comment by tomchadwin** [comment] 2018-09-06 14:54
Duplicate of #411, which I'll reopen.

**Closed by tomchadwin** 2018-09-06 14:54 UTC
