### ISSUE TITLE
Layer Search Does Not Work When Pasting String From Clipboard

### ISSUE THREAD

**Issue by pdpob** [tomchadwin/qgis2web#425] opened 2017-03-02 15:34 UTC
It seems that layer search only works if I type string into the search box. If I copy string, say from a spreadsheet, and paste it into the search box all that happens is the page appears to refresh.

**Comment by tomchadwin** [comment] 2017-03-02 18:20
Confirmed. However, I'm afraid I don't have any solution at this point. Any ideas @stefanocudini, @ThomasG77?

**Comment by tomchadwin** [comment] 2017-03-25 11:25
I'll close this for the moment, since it arises from third-party libs. Do contribute to the issues I have raised on those repos:

- https://github.com/stefanocudini/leaflet-search/issues/154
- https://github.com/webgeodatavore/ol3-search-layer/issues/5

**Closed by tomchadwin** 2017-03-25 11:25 UTC
Labels: bug

**Comment by stefanocudini** [comment] 2017-04-26 00:18
yes the Leaflet Control Search trigger action only when user change or type new text in input box... for paste clipboard I don'r know what event to bind.... 
If you know how it can be done I can write a patch in the next version

**Comment by tomchadwin** [comment] 2017-04-26 08:26
How about binding to an "Enter/return" keypress as a workaround? Or does that happen already?

**Comment by stefanocudini** [comment] 2017-04-26 14:30
the plugin just binded the Enter key press

**Comment by iofirag** [comment] 2018-10-10 07:54
i also stuck with that issue. having any solution so far?

**Comment by tomchadwin** [comment] 2018-10-10 08:00
@stefanocudini How about binding to the `change` event?

**Comment by stefanocudini** [comment] 2018-10-10 08:17
hi @tomchadwin today I'll try to adapt events bind fo this case ;-)

**Comment by iofirag** [comment] 2018-10-10 08:30
better that, you can bind it to new html5 attribute called '**onpaste**'.
by that it can fix the problem i think.

`<input onpaste="myFunction()" />`

[https://developer.mozilla.org/en-US/docs/Web/Events/paste](https://developer.mozilla.org/en-US/docs/Web/Events/paste)

your can see my demo here:
[https://www.w3schools.com/code/tryit.asp?filename=FW48HGM5HSU0](https://www.w3schools.com/code/tryit.asp?filename=FW48HGM5HSU0)

**Comment by tomchadwin** [comment] 2018-10-10 08:52
@iofirag Nice! I didn't know about that.

**Comment by stefanocudini** [comment] 2018-10-10 08:58
tnk @iofirag 

I think that the browsers support cloud be enough:
https://caniuse.com/#search=paste

**Comment by tomchadwin** [comment] 2018-10-10 08:59
@stefanocudini All I would say is that the version of Webkit used as the qgis2web preview lags behind, and might not support it. But then, it already doesn't support various aspects of the maps qgis2web produces.

**Comment by iofirag** [comment] 2018-10-11 10:34
you are king! thanks.
:1st_place_medal:
