### ISSUE TITLE
Issue for exporting and previsualising

### ISSUE THREAD

**Issue by maximehua** [tomchadwin/qgis2web#881] opened 2020-05-13 08:57 UTC
Hi ! 

When I try to export or visualize my webmap, I have the issue below.

Do you have an explanation?

`Une erreur est survenue lors de l'éxécution du code Python: 

KeyError: 'layout' 
Traceback (most recent call last):
  File "C:/Users/mhua.proxemys/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\mapboxStyleScripts.py", line 76, in getLayerStyle
    for prop in layer["layout"]:
KeyError: 'layout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/mhua.proxemys/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 190, in changeFormat
    self.autoUpdatePreview()
  File "C:/Users/mhua.proxemys/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 334, in autoUpdatePreview
    self.previewMap()
  File "C:/Users/mhua.proxemys/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 337, in previewMap
    preview_file = self.createPreview()
  File "C:/Users/mhua.proxemys/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 300, in createPreview
    dest_folder=utils.tempFolder()).index_file
  File "C:/Users/mhua.proxemys/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\mapboxWriter.py", line 104, in write
    folder=dest_folder)
  File "C:/Users/mhua.proxemys/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\mapboxWriter.py", line 296, in writeMapbox
    useOSMB, vtSources, layers)
  File "C:/Users/mhua.proxemys/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\mapboxLayerScripts.py", line 145, in writeVectorLayer
    mblayers = getLayerStyle(layer)
  File "C:/Users/mhua.proxemys/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\mapboxStyleScripts.py", line 82, in getLayerStyle
    layer["layout"][prop]]
KeyError: 'layout'

Version de Python : 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Version de QGIS : 3.12.2-București București, 8a1fb33634 

Chemin Python :
C:/QGIS/apps/qgis/./python
C:/Users/mhua.proxemys/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/mhua.proxemys/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/QGIS/apps/qgis/./python/plugins
C:\QGIS\apps\Python37
C:\QGIS\apps\Python37\Scripts
C:\QGIS\bin\python37.zip
C:\QGIS\apps\Python37\DLLs
C:\QGIS\apps\Python37\lib
C:\QGIS\bin
C:\QGIS\apps\Python37\lib\site-packages
C:\QGIS\apps\Python37\lib\site-packages\win32
C:\QGIS\apps\Python37\lib\site-packages\win32\lib
C:\QGIS\apps\Python37\lib\site-packages\Pythonwin
C:/Users/mhua.proxemys/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/mhua.proxemys/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\mhua.proxemys\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:/Données/1. Dossier DUPm Est/3. Dossier final & fichiers sources/MECDU`

**Comment by tomchadwin** [comment] 2020-05-13 09:26
Duplicate of #866?

**Closed by tomchadwin** 2020-05-13 09:26 UTC
