### ISSUE TITLE
no result

### ISSUE THREAD

**Issue by Jorishin** [tomchadwin/qgis2web#354] opened 2016-10-31 00:21 UTC
I made a nice map, which’d like to publish online.
my map gives no result when trying to export with QGIS2Web.

I’m just a poor lonesome mapper, and know nothing about coding, I cannot even define what the issue is.

more info at
https://dl.dropboxusercontent.com/u/23700421/refugeemapData.zip

with this link you can find:
- A consolidated project including all data (made in QGIS 2.14 on MacOS10.11)
  -some screen grabs from the Qgis2web UI with results and/or error messages

as you can see, result is far from the original.

Thanks for having a look at it.

joris

**Comment by tomchadwin** [comment] 2016-10-31 11:17
I don't know the cause of this error. I've asked for help on the QGIS user mailing list. It's related to the project CRS. If I find out anything more, I'll get back to you. I can tell you that grids/graticules are not supported (yet).

**Comment by boesiii** [comment] 2016-10-31 14:10
I think the issue has something to do with how gdal is calculating the extents.  If you choose the option "Fit to layers extent", it does work although the export does not look anything like the map.

**Comment by Jorishin** [comment] 2016-10-31 20:38
the extent is only part of the problem. Tony Pham succeeded (see maillist) in making a map with my data, leaving out the concatenated lables and the manually created (logarithmic) color scales.

thanks for your input

Joris

**Comment by tomchadwin** [comment] 2016-11-01 10:10
Expressions in labels are indeed unsupported: see #302. I wasn't aware of the other issue with the colour scale. Are you sure that causes a problem, if the extent and label problems are removed?

**Comment by kelv-cz** [comment] 2016-11-02 09:05
Please make screenshot in qgis. Qgis2web needs specific settings when they categorized by attribute. Sometimes I had empty result too.

**Comment by tomchadwin** [comment] 2016-11-02 09:19
@kelv-cz I've not experienced that, so it would be good to find examples that fail.

**Comment by kelv-cz** [comment] 2016-11-02 11:16
1) Different bug: Leaflet export with not styled layer (end of the video): https://www.youtube.com/watch?v=NgOJWbW_0iI  (maybe fixed in 1.19).

2) Maybe this issue. If layers are alone then result ok. But, if they are in group (folder for layers), then openlayer3  - empty preview; Leaflet preview:  Erro ... AttributeError: 'int' object has no attribute 'keys'
Do not use groups (maybe fixed in 1.19).

**Comment by Jorishin** [comment] 2016-11-02 20:20
screenshots and projectfile are on dropbox:
https://dl.dropboxusercontent.com/u/23700421/refugeemapData.zip <https://dl.dropboxusercontent.com/u/23700421/refugeemapData.zip>

**Comment by kelv-cz** [comment] 2016-11-02 20:22
Try new map project wit a few of layers.

**Comment by kelv-cz** [comment] 2016-11-02 20:43
Export is working.  (qgis2qeb 1.18) http://r.kelv.cz/

**Comment by Jorishin** [comment] 2016-11-02 20:48
Great! But…

You took the data layer, but not the styling and the projection. 
I liked the look of my own map so much… I try to make my maps look neat, not just transmitting info.
And that neat maps, I’d like to share online. 

If 
Joris

**Comment by kelv-cz** [comment] 2016-11-02 20:52
Maybe some style not compatible with qgis2web or leaflet.

**Comment by Jorishin** [comment] 2016-11-02 21:01
My original maps contains the following elements that are (maybe) incompatible :

Shading
Projection Mollweide (EPSG53009)that results in view of >360°
manually defined categorized styling (simulating a logarithmic scale)
concatenated labels

Tony Phan sent me this email earlier this week:

Hello Joris,
 
Using your QGIS specific project file, I did receive error messages when trying to generate a qgis2web-based Leaflet or OpenLayers 3 web page of your map. I believe there are a few settings in your existing project file that produce issues when the QGIS2Web app runs its python script and hence you receive an error output. One example is the label field in which you employ a concatenation of two separate fields. I don’t believe QGIS2Web can handle the concatenation of multiple fields for its label.
 
However, I was able to work around the error and generate a Leaflet-based page by performing the following:
 
1.       Removing the WorldRefug layer with the concatenated label along with all other layers from QGIS
2.       Re-importing the WorldRefug shapefile layer into QGIS
3.       Generating a “Graduated” style (Thematic map) based on UNHRDATNUM with “Equal Interval” mode
4.       Set up the WorldRefug layer such that there is No Label (the Qgis2web app has trouble with concatenating multiple fields for the label setting)
 
Below is a screenshot of my qgis2web pop up app on a Mac platform with a preview of the working web page (I have also attached a PNG image for good measure):

 
Hope this helps!
 
Regards,
-Tony

**Comment by tomchadwin** [comment] 2017-01-25 18:29
Expressions in labels are now supported in master, so please test to see whether concatenation is working for you. Only basic expressions are supported at the moment, so report failures, and we'll see what can be developed.

**Comment by tomchadwin** [comment] 2017-03-26 10:00
Closing because no recent feedback. Reopen if required.

**Closed by tomchadwin** 2017-03-26 10:00 UTC

**Comment by tomchadwin** [comment] 2017-03-27 05:34
Re: projection error, I missed this reply on the mailing list:

http://lists.osgeo.org/pipermail/qgis-user/2016-November/038295.html

Have you tried EPSG:53009 instead?
