### ISSUE TITLE
Unable to handle non-ascii filenames/layernames?

### ISSUE THREAD

**Issue by gusbo** [tomchadwin/qgis2web#152] opened 2015-11-19 14:49 UTC
Got this traceback:
I suspect it is because of my swedish layer names and/or filenames.

Traceback (most recent call last):
File "C:/Users/Gustav/.qgis2/python/plugins\qgis2web\maindialog.py", line 110, in previewMap
MainDialog.previewOL3(self)
File "C:/Users/Gustav/.qgis2/python/plugins\qgis2web\maindialog.py", line 278, in previewOL3
cluster, labels, params, utils.tempFolder())
File "C:/Users/Gustav/.qgis2/python/plugins\qgis2web\olwriter.py", line 58, in writeOL
exportLayers(layers, folder, precision, optimize, usedFields)
File "C:/Users/Gustav/.qgis2/python/plugins\qgis2web\utils.py", line 129, in exportLayers
universal_newlines=False)
File "C:\PROGRA~1\QGISLY~1\apps\Python27\lib\subprocess.py", line 711, in __init__
errread, errwrite)
File "C:\PROGRA~1\QGISLY~1\apps\Python27\lib\subprocess.py", line 922, in _execute_child
args = '{} /c "{}"'.format (comspec, args)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd6' in position 101: ordinal not in range(128)

**Comment by gusbo** [comment] 2015-11-19 15:07
Doesn't seem to be layer names or group names. More likely som folder name in the project path.

**Comment by tomchadwin** [comment] 2015-11-19 15:48
From where the error occurs, do I take it that this is a raster? In other words, the problem is not attributes or values?

**Comment by gusbo** [comment] 2015-11-19 16:41
No, it could be attributes as well.
The project I tested was a huge one with many rasters and vector layers.
I will try to investigate further. Is there a way to debug  the plugin?
I'm a relatively experienced Python developer, so I might be able to get
more info.
Den 19 nov 2015 4:48 em skrev "Tom Chadwin" <notifications@github.com>:

**Comment by tomchadwin** [comment] 2015-11-19 17:00
Try to isolate which layer(s) on their own cause issues, then we can look at those. The error appeared not to be with the plugin itself, but either with subprocess, or gdal_translate which it called. No idea about those, I'm afraid.

**Comment by gusbo** [comment] 2015-11-19 22:41
I will have a look. Maybe the subprocess call needs an encoding spec.

2015-11-19 18:00 GMT+01:00 Tom Chadwin <notifications@github.com>:

**Comment by tomchadwin** [comment] 2015-12-02 16:03
Closing for now with no feedback. Reopen when required.

**Closed by tomchadwin** 2015-12-02 16:03 UTC
