### ISSUE TITLE
Multiple layers disappear/reappear when switching off/on layers

### ISSUE THREAD

**Issue by lewisdjl** [tomchadwin/qgis2web#642] opened 2018-05-14 09:28 UTC
Multiple layers disappear/reappear when switching off/on layers (see powerpoint screenshot)
Using latest version of QGIS2WEB (3.1.0) in QGIS version 3.0.2.
Also when dragging map in web window the layers that should be showing, but aren't, become visible but then disappear when you release the left mouse button.
Any assistance would be greatly appreciated,
Debug attached.
thanks
David

[index.zip](https://github.com/tomchadwin/qgis2web/files/2000090/index.zip)

[QGIS2WEB Issue.pptx](https://github.com/tomchadwin/qgis2web/files/2000040/QGIS2WEB.Issue.pptx)
To ensure no time or effort is wasted in bug reporting, please follow these steps:

1. Make sure you are using the latest release of qgis2web
2. Check the issues on Github to see whether the bug has already been reported, and if so, read through all the comments on the issue, and add any additional information from your experience of the bug
3. Make sure you can reproduce the bug reliably
4. Reduce the complexity of your bug conditions as far as you can, especially by reducing the number of layers, ideally to one
5. Raise a Github issue, including:
  - only one bug per Github issue
  - the qgis2web version (or make it clear you are using Github master branch)
  - any Python error text/stack trace which occurs
  - browser JS console errors - press F12 in qgis2web to open the developer toolbar and find the console
  - screenshot of your settings
  - screenshot of the output
  - a link to the data you used, if possible

**Comment by tomchadwin** [comment] 2018-05-14 09:35
This is caused by the declutter process in OpenLayers. You have two options:

- export in Leaflet format instead
- if using OpenLayers, from your exported webmap, open `layers/layers.js` in a text editor, and remove all occurrences of `declutter: true,`

I don't understand why declutter is not working very well, but it isn't in qgis2web. I'd love it if @ahocevar could take a look. I'll close this issue for now, as there might be an existing one about OpenLayers declutter failing.

**Closed by tomchadwin** 2018-05-14 09:35 UTC

**Comment by lewisdjl** [comment] 2018-05-14 13:52
Thanks Tom for your response.
This solution works perfectly. A shame I need to do it every time I publish a map to the web but hopefully this will only be in the short-term.

**Comment by enadol** [comment] 2018-05-16 17:25
Removing declutter : true in layers.js works fine to me (Windows 10)

**Comment by tomchadwin** [comment] 2018-05-18 16:14
Released as 3.1.1 and pushed to QGIS plugins repo.

**Comment by lewisdjl** [comment] 2018-05-21 09:01
Thanks for this!!
Regards
David


David Lewis
Senior Information Specialist,
Finance, Contracting and Business Intelligence

NHS Northern, Eastern and Western Devon Clinical Commissioning Group
Direct Dial: 01392 267677| Email: david.lewis6@nhs.net<mailto:david.lewis6@nhs.net>
NEW Devon CCG | 2nd Floor Main Building|County Hall |Topsham Road | Exeter |EX2 4QL
[Description: Description: NHS2]
Healthy people, living healthy lives, in healthy communities
