### ISSUE TITLE
How to remove duplicated labels

### ISSUE THREAD

**Issue by anncerr100** [tomchadwin/qgis2web#353] opened 2016-10-28 21:12 UTC
In QGIS, I have 'Label every part of multi-part features' unchecked.
I use qgis2web-> create web map, I see there are duplicated labels for multi part features.
My QGIS version is 2.16.3

**Comment by tomchadwin** [comment] 2016-10-30 08:09
Duplicate of #237

**Closed by tomchadwin** 2016-10-30 08:09 UTC
