### ISSUE TITLE
error icon svg with diffrent category  leaflet

### ISSUE THREAD

**Issue by warty123** [tomchadwin/qgis2web#328] opened 2016-08-24 23:50 UTC
Error

qgis2web produced an error:

Traceback (most recent call last):
File "C:/Users/Dell/.qgis2/python/plugins\qgis2web\maindialog.py", line 133, in previewMap
MainDialog.previewLeaflet(self)
File "C:/Users/Dell/.qgis2/python/plugins\qgis2web\maindialog.py", line 301, in previewLeaflet
visible, cluster, json, params, popup)
File "C:/Users/Dell/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 152, in writeLeaflet
canvas)
File "C:/Users/Dell/.qgis2/python/plugins\qgis2web\leafletLayerScripts.py", line 292, in writeVectorLayer
json, wfsLayers)
File "C:/Users/Dell/.qgis2/python/plugins\qgis2web\leafletLayerScripts.py", line 619, in categorizedLayer
catLegend)
File "C:/Users/Dell/.qgis2/python/plugins\qgis2web\leafletLayerScripts.py", line 662, in categorizedPoint
border_transp = float(symbolLayer.borderColor().alpha()) / 255
AttributeError: 'QgsSvgMarkerSymbolLayerV2' object has no attribute 'borderColor'

I have different points and classifies them into different things, for example a hospital etc. and need to use icon svg
what I need to do to not have this error and add symbols

soorry for my bad english
Regards

**Comment by tomchadwin** [comment] 2016-08-25 10:49
So you are doing the following:

- categorized symbology
- SVG marker symbol
- Leaflet format

?

**Comment by tomchadwin** [comment] 2016-08-25 10:51
If so, confirmed.

**Comment by tomchadwin** [comment] 2016-09-07 16:51
Partial fix committed to master. This no longer crashes, but it also doesn't use the SVG symbol. Please at least let me know if the crash is gone.

**Comment by tomchadwin** [comment] 2016-09-13 15:31
Closing, duplicate of #262

**Closed by tomchadwin** 2016-09-13 15:31 UTC
Labels: bug, Leaflet, styles, vectors
