### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'dump'

### ISSUE THREAD

**Issue by joshco** [tomchadwin/qgis2web#149] opened 2015-11-10 04:37 UTC
I'm getting this error when I click the button for create web map
I have 3 layers, 1 from csv which is joined to 2 shp maps.
````
2015-11-09T23:33:29	1	Traceback (most recent call last):
			  File "C:/Users/Josh/.qgis2/python/plugins\qgis2web\qgis2web.py", line 51, in run
			    dlg = MainDialog(self.iface)
			  File "C:/Users/Josh/.qgis2/python/plugins\qgis2web\maindialog.py", line 53, in __init__
			    self.populate_layers_and_groups(self)
			  File "C:/Users/Josh/.qgis2/python/plugins\qgis2web\maindialog.py", line 155, in populate_layers_and_groups
			    testDump = layer.rendererV2().dump()
````

**Comment by tomchadwin** [comment] 2015-11-11 12:02
This looks like the same issue which was reported as part of #93. It was fixed in https://github.com/tomchadwin/qgis2web/commit/390431c974b6b46fce53598cc0a6fd7fce6f6783, but it looks as though I introduced a regression in https://github.com/tomchadwin/qgis2web/commit/4a057a28585a9359faf37e69861fbcf10eabb09c. I'll try to reimplement the fix from https://github.com/tomchadwin/qgis2web/commit/390431c974b6b46fce53598cc0a6fd7fce6f6783.

**Comment by tomchadwin** [comment] 2015-11-11 12:10
Can you try master now? I've redone the fix.

Please note, though: I've been doing a whole load of code refactoring since the last release. Let me know if anything else appears not to be working.

**Closed by tomchadwin** 2015-11-11 12:10 UTC
Labels: bug

**Comment by meneos** [comment] 2017-09-08 09:26
I'm having the same problem. I have the latest version of qgis2web and the lates version of QGIS (Las Palmas 2.18), the map I'm trying to export consists in a shp graduate layer that is joined to a dataset layer and a third layer that shows only the border lines of the districts. I am able to export similar maps.

This is the mesage that I get:

> 2017-09-08T11:21:02	1	Traceback (most recent call last):
			  File "/Users/HECTOR/.qgis2/python/plugins/qgis2web/qgis2web.py", line 58, in run
			    self.dlg = MainDialog(self.iface)
			  File "/Users/HECTOR/.qgis2/python/plugins/qgis2web/maindialog.py", line 86, in __init__
			    self.setupUi(self)
			  File "/Users/HECTOR/.qgis2/python/plugins/qgis2web/ui_maindialog.py", line 180, in setupUi
			    uitime = Ui_TimeDialog(self.tabWidget, MainDialog)
			  File "/Users/HECTOR/.qgis2/python/plugins/qgis2web/ui_timedialog.py", line 54, in __init__
			    self.populate_layers_and_groups(self)
			  File "/Users/HECTOR/.qgis2/python/plugins/qgis2web/ui_timedialog.py", line 80, in populate_layers_and_groups
			    testDump = layer.rendererV2().dump()
			AttributeError: 'NoneType' object has no attribute 'dump'

**Comment by tomchadwin** [comment] 2017-09-08 10:47
I think that is the same issue as https://github.com/tomchadwin/qgis2web/issues/536, and has already been fixed. Can you try master branch from here on Github to see if that solves the problem?

**Comment by meneos** [comment] 2017-09-08 16:09
It worked!. Thanks for this and for the plugin. It's great
