### ISSUE TITLE
Control.OSMGeocoder

### ISSUE THREAD

**Issue by azstumbler** [tomchadwin/qgis2web#426] opened 2017-03-02 23:37 UTC
http://k4r573n.github.io/leaflet-control-osm-geocoder/Control.OSMGeocoder.js is no longer valid for the OSMgeocoder. The valid location is now  https://rawgit.com/k4r573n/leaflet-control-osm-geocoder/master/Control.OSMGeocoder.js yet the most current version of QGIS2Web keeps directing to the invalid location.

**Comment by tomchadwin** [comment] 2017-03-03 00:03
Duplicate of #421. 2.7.0 released this evening which should include the fix.

**Closed by tomchadwin** 2017-03-03 00:03 UTC
