### ISSUE TITLE
Ol3 label are very small (unreadable) and over the points

### ISSUE THREAD

**Issue by marcobra** [tomchadwin/qgis2web#116] opened 2015-09-22 14:15 UTC
Hi Tom, the openlayer is rendering as showed in this image:

![1](https://cloud.githubusercontent.com/assets/1607387/10020782/0a202820-6145-11e5-9fb4-a02204672627.png)

Please dress it
Thank

**Comment by tomchadwin** [comment] 2015-09-22 14:21
Confirmed. Let me look into it.

**Comment by tomchadwin** [comment] 2015-09-22 14:36
Committed a "fix" to master. I've used fairly arbitrary values for a font size multiplier and x and y offsets. Please let me know what you think.

**Comment by marcobra** [comment] 2015-09-22 14:46
size = layer.customProperty("labeling/fontSize") * 1.5 made preview not showed
removing it, the preview work, the offset of points is better, i will suggest you my best value

**Comment by tomchadwin** [comment] 2015-09-22 14:48
That's odd. It works for me.

**Comment by marcobra** [comment] 2015-09-22 14:51
My best set here is    
offsetX: 8
offsetY: 0

**Comment by marcobra** [comment] 2015-09-22 16:06
Using the test file you sent PM to me the error showed here is:

size = layer.customProperty("labeling/fontSize") * 1.5
TypeError: can't multiply sequence by non-int of type 'float'

then setting 

size = float(layer.customProperty("labeling/fontSize")) * 1.5
works

So i get my best rendering by set

float(layer.customProperty("labeling/fontSize")) * 1.3
...
offsetX: 10,
offsetY: 0,

in olwriter.py

**Comment by tomchadwin** [comment] 2015-09-22 16:30
Committed to master. Can you test to see if you get the results you want?

**Comment by marcobra** [comment] 2015-09-22 16:34
for me is working tested with above sample data...

**Comment by tomchadwin** [comment] 2015-09-22 16:51
Great. I'll release as soon as I can.

**Closed by tomchadwin** 2015-09-22 16:51 UTC
Labels: bug, OL3

**Comment by tomchadwin** [comment] 2015-09-23 11:11
Released as 0.24.0 and pushed to QGIS plugins repo
