### ISSUE TITLE
popup word wrap

### ISSUE THREAD

**Issue by jukos** [tomchadwin/qgis2web#836] opened 2019-11-13 17:54 UTC
Hello,
I have problems with the word wrap of webseite URL. 
Please look at the my image with two screenshots:
![Umbruch](https://user-images.githubusercontent.com/31866672/68790027-d8067280-0646-11ea-8862-d43f66c11c04.png)
Is this a bug? Or can I do a change within the css to solve the problem?

Thank you and greetings, Jürgen

**Comment by jukos** [comment] 2019-12-04 08:45
For the html/css I found not really a good solution. Only scroll horizontal, but it looks like not good.
But I use another easy solution for long URL:
<a href="LINK" target="_blank">TEXT</a> 
So the URL is short and better to read.
Greetings

**Comment by tomchadwin** [comment] 2019-12-04 16:25
The issue is that I'm not sure that any solution exists, other than the horizontal scroll bar.

**Comment by riccardoklinger** [comment] 2019-12-22 20:24
how about skipping this whole discussion and using a <a href="VERY LONG URL">Link</a> approach... as Jürgen explained. cleaner and easier to read.
@tomchadwin what is your opinion?

**Comment by tomchadwin** [comment] 2020-01-08 09:13
@riccardoklinger You mean always use the text "LINK" (or whatever)? I'm not keen, as that's an absolute no-no for accessibility:

> **2.4.4 Link Purpose (In Context):** The purpose of each link can be determined from the link text alone or from the link text together with its programmatically determined link context, except where the purpose of the link would be ambiguous to users in general. 

(https://www.w3.org/TR/WCAG20/#navigation-mechanisms)

**Comment by tomchadwin** [comment] 2020-01-09 09:46
I think I've got a good solution, but I'd be grateful if someone tested before I implemented it. We already use Autolinker to make the links. It has a `truncate` option, which allows you to set a max length for the displayed text. That would do the job perfectly. I don't know if we'll need to update the Autolinker version we currently bundle.

**Comment by tomchadwin** [comment] 2020-01-09 10:14
OK, I've committed this to master, with the truncate `length` property set to 30 (after minimal testing). Can you test and report back?

**Comment by jukos** [comment] 2020-01-09 20:53
I have made a test:
I have had problems with images within the popups. After first click  the popup was too small for the width of the image. All my images have the width: 300px. 
Second click: Ok 
After use the regular version: all ok. I have replaced the whole folder "qgis2web".

It seems, that you idea for reduced long URLs are good. But I think we need one more test/s.....
Maybe riccardo can also do a test.
Greetings, Jürgen

**Comment by tomchadwin** [comment] 2020-01-10 09:01
@jukos Which output map format?

**Comment by jukos** [comment] 2020-01-10 10:24
leaflet

**Comment by tomchadwin** [comment] 2020-01-10 11:31
I think this is a different issue. It occurs for me without the change I just made (ie without `truncate`). I guess it needs to be a different issue, then. I'll close this one again.

**Closed by tomchadwin** 2020-01-10 11:31 UTC
