### ISSUE TITLE
Error when exporting to OpenLayers and Leaflet

### ISSUE THREAD

**Issue by 1900g** [tomchadwin/qgis2web#640] opened 2018-05-02 08:47 UTC
Si è verificato un errore durante l'esecuzione del codice Python: 

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 554: ordinal not in range(128) 
Traceback (most recent call last):
  File "/Users/gio1/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 327, in saveMap
    feedback=self.feedback)
  File "/Users/gio1/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletWriter.py", line 101, in write
    folder=dest_folder)
  File "/Users/gio1/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletWriter.py", line 188, in writeLeaflet
    exp_crs, minify)
  File "/Users/gio1/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/utils.py", line 209, in exportVector
    for line in tmpFile:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 554: ordinal not in range(128)

Versione Python: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] 
Versione di QGIS: 3.0.2-Girona Girona, exported

**Comment by tomchadwin** [comment] 2018-05-02 08:59
Duplicate of #624. I'll close this issue. Can you upload your layer file to that issue - I'm not having any joy finding the cause for this. Last user's data I could export fine.

**Closed by tomchadwin** 2018-05-02 08:59 UTC

**Comment by tomchadwin** [comment] 2018-05-02 14:53
Fix committed to master. Please test.

**Comment by tomchadwin** [comment] 2018-05-02 17:14
Released as 3.1.0 and pushed to QGIS plugins repo.
