### ISSUE TITLE
last release breaks with categorized styles

### ISSUE THREAD

**Issue by Sortronic** [tomchadwin/qgis2web#458] opened 2017-03-29 16:18 UTC
with normal style it works just fine. Adding categorized style with OL3 the map is blank and search layer doesn't show. Leaflet gives an error in Python with long list of problems on which it says "object" not recognized. Sorry, I forgot to write down specific issues, I was very stressed. Got back to Master version 10/03 and it works well. I don't think to have a problem with my QGIS, since the old version works for me, but it would be nice to know if somebody else has the same issue.

**Comment by tomchadwin** [comment] 2017-03-29 17:08
I've not had this problem. An error message really is essential to solve things like this. Or can you share your project and layers?

**Comment by Sortronic** [comment] 2017-03-31 13:15
Sorry for the delay, I was away from my desk. As I said I reverted to a previous version so I cannot replicate the issue, but this is the result I got.
[qgis2web_2017_03_29-11_17_20_061000.zip](https://github.com/tomchadwin/qgis2web/files/885735/qgis2web_2017_03_29-11_17_20_061000.zip)

**Comment by boesiii** [comment] 2017-03-31 13:43
Can you share your original data and qgis project file?

**Comment by Sortronic** [comment] 2017-03-31 14:32
[IndianaDigitalMap.zip](https://github.com/tomchadwin/qgis2web/files/885919/IndianaDigitalMap.zip)
I have merged two layers to have 'search layers' function for both. Actually it would be nice to have 'search layer' for independent layers, in my case it would make life much easier for my customers.
At a first glance 'search layer' may not make sense. It is a digital companion of a indexed paper map.
More info here: slowfootmovement.com

**Comment by mulaz** [comment] 2017-03-31 14:36
Same issue here. Some random data from csv (with some lines in wkt). If i leave the default style (all lines same color), everything works. If i set the style to categorized, same issue as @Sortronic. If I change the style back to single symbol, it works. (pretty much with default openlayers settings in qgis2web)

**Comment by tomchadwin** [comment] 2017-03-31 14:37
Thanks for the output, @Sortronic. I think it's shown me where one issue lies, and I'm working on it now. One question for both you and @mulaz: are you categorizing on a *numeric* field?

**Comment by mulaz** [comment] 2017-03-31 14:39
Yes, my field is numeric. I can try appedning some characters infront to make it 'text' if that helps

**Comment by tomchadwin** [comment] 2017-03-31 14:42
@mulaz: no, I'm not sure if expressions in categorized fields are yet supported. You could try categorizing on a string field, and hopefully confirm that the error disappears?

**Comment by mulaz** [comment] 2017-03-31 14:47
I have to categorize by a field that is by default numeric (random object/feature 'ID' ), but I've changed the data in my field from a "$number" to "$text-$number" ( 123 -> ID-123) to make it a string, and if categorized using that field, it works (shows the categorized fields and correct colors). 

So yes, using a string field to categorize data works for me.

**Comment by tomchadwin** [comment] 2017-03-31 14:52
OK. Thanks for letting me know. Having some difficulty fixing this, but still working on it.

**Comment by Sortronic** [comment] 2017-03-31 14:59
In my case is a string field which has letters and numbers.

**Comment by tomchadwin** [comment] 2017-03-31 15:03
@Sortronic Are you sure? The error your output had was:

```AttributeError: 'long' object has no attribute 'replace'
```

Can you both try master branch from here now - I've committed a partial fix. From my testing, though, it possibly only works with integers, not decimals. Or possibly the other way round... Anyway. can you let me know if there's any difference?

**Comment by Sortronic** [comment] 2017-03-31 18:03
it works fine with Master. I don't know what the issue was, I don't think I screwed the first time I did because I have tried several times, but is good now for me, so many thanks.

**Comment by tomchadwin** [comment] 2017-03-31 18:09
No you did nothing wrong. I did. Sorry!

**Comment by tomchadwin** [comment] 2017-03-31 22:42
@mulaz Does this also fix things for you?

**Comment by tomchadwin** [comment] 2017-04-03 13:06
Closing for now - reopen if the problem is not fixed.

**Closed by tomchadwin** 2017-04-03 13:06 UTC

**Comment by eww125** [comment] 2017-09-08 21:39
Hi Tom, I also see this issue when I use qgis2web. It seems like anything categorized or rule-based will only show up as a single style... I am on qgis 2.16.3 which is a little outdated...
