### ISSUE TITLE
Time Extension/Funcionality 

### ISSUE THREAD

**Issue by moni1865** [tomchadwin/qgis2web#742] opened 2019-05-03 02:30 UTC
Sorry, I know this question has been asked and answered before but I am new and confused. The time functionality is not working for me. From previous posts, I gather that I am supposed to export map and then add the time. I did that but when I opened the index-time file nothing was there but two empty boxes from the time slider.Also, my data field format is YYYY but I would prefer YYYY-MM-DD. Please help

**Comment by moni1865** [comment] 2019-05-03 02:54
I figured "export the map, then go back and time." My error was that I was not opening the index-time html file. I also changed my data field format to YYYY. But when I opened the index-time file nothing was there but two empty boxes from the time slider. What am I doing wrong?

**Comment by boesiii** [comment] 2019-05-06 19:49
This is probably the wrong place to ask this question.  This issue tracker is for bug reports and feature requests.  I would suggest that you ask your question at https://gis.stackexchange.com/ and make sure you tag qgis2web.

**Comment by tomchadwin** [comment] 2019-05-07 09:32
Tagging @ruz76

**Comment by ruz76** [comment] 2019-05-12 09:01
@moni1865 Could you please send me some data to test the functionality to jan.ruzicka.vsb@gmail.com There may be hidden things that the code can not process.

**Comment by tomchadwin** [comment] 2019-06-06 10:34
Closing without feedback. Leave a comment if the issue is still present and I can reopen,

**Closed by tomchadwin** 2019-06-06 10:34 UTC

**Comment by wstaelens** [comment] 2023-01-20 13:32
am I correct that this functionality doesn't work?

**Comment by ruz76** [comment] 2023-01-20 17:09
Yes. Sorry about that, but we did not continue the development. The main reason was that the extension was basically hack of existing code, so it was difficult to maintain it.
