### ISSUE TITLE
Line pattern fill - Leaflet crash, OL3 unstyled

### ISSUE THREAD

**Issue by ecodiv** [tomchadwin/qgis2web#275] opened 2016-05-18 08:21 UTC
When trying to export to LeafLet, I am getting the following error message (already on preview):

> Traceback (most recent call last):
> File "/home/paulo/.qgis2/python/plugins/qgis2web/maindialog.py", line 134, in previewMap
> MainDialog.previewLeaflet(self)
> File "/home/paulo/.qgis2/python/plugins/qgis2web/maindialog.py", line 307, in previewLeaflet
> visible, cluster, json, params, popup)
> File "/home/paulo/.qgis2/python/plugins/qgis2web/leafletWriter.py", line 156, in writeLeaflet
> canvas)
> File "/home/paulo/.qgis2/python/plugins/qgis2web/leafletLayerScripts.py", line 186, in writeVectorLayer
> json, wfsLayers)
> File "/home/paulo/.qgis2/python/plugins/qgis2web/leafletLayerScripts.py", line 460, in categorizedLayer
> json, count, popFuncs, wfsLayers)
> File "/home/paulo/.qgis2/python/plugins/qgis2web/leafletLayerScripts.py", line 556, in categorizedPolygon
> border_transp = float(symbolLayer.borderColor().alpha()) / 255
> AttributeError: 'QgsLinePatternFillSymbolLayer' object has no attribute 'borderColor'

Any idea?

**Comment by tomchadwin** [comment] 2016-05-18 10:24
It's because the fill style of one of your symbols is not supported (Line pattern fill?). I need to trap the error in the plugin and get it to fail over to another style. Presumably although it exports in OL3, that fill style is not correctly reproduced? In the meantime, change to a simple fill in QGIS, and it should work. Let us know.

**Comment by ecodiv** [comment] 2016-05-31 07:25
Ah, yes, forgot about the line pattern fill. Replaced it and now it works. Thanks! 

You are right about the export in OL3, the polygons with line pattern fill are displayed without fill / white when exported.

**Comment by tomchadwin** [comment] 2016-05-31 10:52
OK - so improvement can be made. Thanks!

**Comment by tomchadwin** [comment] 2017-09-15 15:51
Line pattern fill basic support is now in master for Leaflet exports. Can anyone test and report back? The `distance` property is not yet supported: https://github.com/teastman/Leaflet.pattern/issues/15

**Comment by tomchadwin** [comment] 2017-09-20 09:25
This seems to have stopped working. The code looks right, no errors, but no fill. Can anyone confirm or deny, or figure out what is wrong?

**Comment by tomchadwin** [comment] 2017-09-20 09:33
OK, the `weight` value is too low - don't know why. Investigating.

**Comment by tomchadwin** [comment] 2017-09-20 10:24
Fix committed to master. Please test.

**Comment by tomchadwin** [comment] 2017-09-20 18:54
Apologies - I should not have closed this without OL implemented. I got the beginnings of a prototype working today, so hopefully there will soon be an OL version to test.

**Comment by tomchadwin** [comment] 2017-09-23 11:07
OL now working in master. Please test.

**Closed by tomchadwin** 2017-09-23 11:07 UTC
