### ISSUE TITLE
Error when Preview & Export both OpenLayers and Leaflet

### ISSUE THREAD

**Issue by Hazel9527** [tomchadwin/qgis2web#654] opened 2018-06-26 09:11 UTC
Hi tomchadwin, 

I have suddenly experience the error since yesterday. The web mapping is working before. Until then I have received the python error message as below. Since I changed the openstreet map to EPSG:2326, then it couldn't work anymore. It has been working well previously and I still using the same CRS. I have no idea whats going on. I have tried to replace the folder of qgis2web (from you page [Clone or download] button)

Please help!!!
P.S. I am now using the QGIS 3.2 (the latest version)

Many Thanks

(Error message)
An error has occurred while executing Python code: 

_core.QgsCsException: Could not transform bounding box to target CRS 
Traceback (most recent call last):
  File "C:/Users/ilo37/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\qgis2web.py", line 60, in run
    self.dlg = MainDialog(self.iface)
  File "C:/Users/ilo37/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 156, in __init__
    self.autoUpdatePreview()
  File "C:/Users/ilo37/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 319, in autoUpdatePreview
    self.previewMap()
  File "C:/Users/ilo37/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 322, in previewMap
    preview_file = self.createPreview()
  File "C:/Users/ilo37/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 285, in createPreview
    dest_folder=utils.tempFolder()).index_file
  File "C:/Users/ilo37/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 100, in write
    folder=dest_folder)
  File "C:/Users/ilo37/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 226, in writeLeaflet
    pt1 = xform.transformBoundingBox(pt0)
_core.QgsCsException: Could not transform bounding box to target CRS

Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS version: 3.2.0-Bonn Bonn, bc43194061 

Python Path:
C:/PROGRA~1/QGIS3~1.2/apps/qgis/./python
C:/Users/ilo37/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/ilo37/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.2/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.2\bin\python36.zip
C:\PROGRA~1\QGIS3~1.2\apps\Python36\DLLs
C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib
C:\Program Files\QGIS 3.2\bin
C:\PROGRA~1\QGIS3~1.2\apps\Python36
C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages
C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\Pythonwin
C:/Users/ilo37/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\ilo37\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins

**Comment by tomchadwin** [comment] 2018-06-26 09:19
Can you upload your QGIS project file? I've never seen that error before, but it is definitely related to your CRS. If you revert back to the CRS you were previously using, does the error disappear?

**Comment by Hazel9527** [comment] 2018-06-26 09:34
Hi, 
Thanks for a quick reply. 
I have tried the CRS such as 4326  , it can work, but every layers turns to a line except the openlayer map & 3857 as below png. . I have no idea whats going on, therefore I thought I install the latest version of QGIS would help. 

![espg 3857](https://user-images.githubusercontent.com/40595540/41902894-1f2452d6-7967-11e8-88e4-5ffefadc2ea3.png)


Besides, I would like to know how could I upload the project, is that I upload every shp. gpkg. files as well, together in a zip file?

**Comment by tomchadwin** [comment] 2018-06-26 09:41
Yes, zip them together, and then drag the zip onto a reply on this thread. I hope the layers are not huge, though...

I'm not 100% sure exactly what the issue is which you are describing. Is there any way you can show me a version which is correct (from before this issue arose) so I can understand it better?

**Comment by Hazel9527** [comment] 2018-06-26 09:48
[My project.zip](https://github.com/tomchadwin/qgis2web/files/2136581/My.project.zip)
The correct version is, just like an online interactive map, u can click the polygon, look at the detail as i input in attribute table, just like identify within the QGIS, but in web version, so other could not change those items. it looks good in EPSG: 2326 & 4326, but no idea whats happen in qgis2web.

**Comment by tomchadwin** [comment] 2018-06-26 10:47
So are you saying the qgis2web worked with this before? If so, specifically what change have you made which then resulted in the error.

I don't understand why the error is occurring. I have asked for help, as coordinate systems are not a strength of mine.

**Comment by Hazel9527** [comment] 2018-06-28 01:03
I have tried to use EPSG 4326, which is QGIS default to create new polygons within this CRS. However, it still has the same result, every polygon turns to a straight line in preview and export to the web as well

**Comment by tomchadwin** [comment] 2018-09-21 09:09
I'm afraid I don't really understand how you are using/changing CRSes, so I'll close this for now. If you can provide step-by-step instructions on how to produce the error, I can reopen this issue.

**Closed by tomchadwin** 2018-09-21 09:09 UTC

**Comment by mazzma12** [comment] 2018-10-09 13:51
Had something similar and it got solved after unticking the box "Match project CRS"
