### ISSUE TITLE
error with a xls file

### ISSUE THREAD

**Issue by LJ16** [tomchadwin/qgis2web#536] opened 2017-09-03 14:02 UTC
Hi
when my project have loaded a xls file, the plugin report
``Erreur Python: Une erreur est survenue lors de l'éxécution du code Python: Voir le journal des erreurs Python pour plus de détails``
when i delete this file, it's ok

LJ

**Comment by tomchadwin** [comment] 2017-09-04 14:39
Are there no further details in the error message? If there are, can you paste them here? If not, can you look for errors in the Python log (View > Panels > Log Messages Panel > Python error)?

**Comment by tomchadwin** [comment] 2017-09-04 16:10
I've committed a change to master to prevent an error resulting, but I can't confirm this will be the same as your issue. Can you test and report back?

**Closed by tomchadwin** 2017-09-04 16:10 UTC

**Comment by arjan22** [comment] 2017-09-05 09:08
Hi,

I had the same problem as LJ16 discibed, I tried the fix and the problem is solved for me. 

thanks.

**Comment by tomchadwin** [comment] 2017-09-05 18:34
Thanks for letting me know, @aran 22.
