### ISSUE TITLE
qgis2web preview error

### ISSUE THREAD

**Issue by JesusLopTem** [tomchadwin/qgis2web#631] opened 2018-03-27 09:35 UTC
Latest qgis2web version on QGIS3 for Mac (OSX 10.11.6). Every time I try to preview map the plugin gives me this error and no preview is generated:

`2018-03-27T11:18:27	WARNING	Traceback (most recent call last):
			  File "/Volumes/Suevia/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 313, in previewMap
			    preview_file = self.createPreview()
			  File "/Volumes/Suevia/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 276, in createPreview
			    dest_folder=utils.tempFolder()).index_file
			  File "/Volumes/Suevia/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olwriter.py", line 90, in write
			    folder=dest_folder)
			  File "/Volumes/Suevia/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olwriter.py", line 129, in writeOL
			    popup, json, restrictToExtent, extent, feedback, matchCRS)
			  File "/Volumes/Suevia/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/utils.py", line 182, in exportLayers
			    iface, extent, precision, crs, optimize)
			  File "/Volumes/Suevia/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/utils.py", line 209, in exportVector
			    for line in tmpFile:
			  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
			    return codecs.ascii_decode(input, self.errors)[0]
			UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 7311: ordinal not in range(128)`

**Comment by tomchadwin** [comment] 2018-04-19 10:36
Duplicate of #624 - sample data needed to debug this. Please upload the layer file to that other issue. Thanks.

**Closed by tomchadwin** 2018-04-19 10:36 UTC

**Comment by 4nnabe** [comment] 2018-04-27 07:38
I get the same error using qgis2web with QGIS3 (OSX 10.12.6):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6935: ordinal not in range(128) 
There are no special characters in the column names or in the file name, just the fields of my shape-file-data contain special characters (like ü & ß). I would be grateful for any ideas on how to solve this.
![bildschirmfoto 2018-04-27 um 09 37 21](https://user-images.githubusercontent.com/17744038/39350540-c2c60602-49fe-11e8-8694-1a01b9aab6ed.png)

**Comment by tomchadwin** [comment] 2018-04-27 13:40
I've just added a ß to my test data, and get no error. I'm afraid I probably really need you to upload your project and layer files.

**Comment by 4nnabe** [comment] 2018-04-28 07:11
Thanks for looking at it. Unfortunately I cannot upload the shapefile mentioned above due to licensing issues, but I attach a project file and shape file which give me the same error. I hope that will help.
[Test_qgis2web.zip](https://github.com/tomchadwin/qgis2web/files/1957391/Test_qgis2web.zip)

**Comment by tomchadwin** [comment] 2018-04-30 09:40
Thanks for the data. This is odd. No problem for me with that project, either exporting as OpenLayers or Leaflet. I'm using current master, but I'm pretty sure there have been no changes to that code since 3.0.1. I don't suppose there is another Mac user listening in who could try to comment?

One other thing I guess I can try - what's your locale set to? Check Settings > Options > General in QGIS - it will tell you what your system locale is if it's not overridden in QGIS. I can then try changing my QGIS locale to match.

**Comment by 4nnabe** [comment] 2018-05-01 07:49
That's odd indeed. It's using the German settings (de_DE). If I change that to American English, the error is still the same. When I press "update preview" or "export" I get "UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3148: ordinal not in range(128)" using the test data.

**Comment by tomchadwin** [comment] 2018-05-02 08:58
I'll reopen #624 - can we move discussion to there? There are too many duplicates of this issue, and we need to concentrate in one place.

**Comment by tomchadwin** [comment] 2018-05-02 17:15
Released as 3.1.0 and pushed to QGIS plugins repo.
