### ISSUE TITLE
Clearing Attribute Filter

### ISSUE THREAD

**Issue by DLevasheff** [tomchadwin/qgis2web#870] opened 2020-04-20 00:43 UTC
I'm new to all this here, but just found this plugin, it is really cool. I notice that the 'clear filter' function appears disabled and definitely does not work for me. Is this a coming feature or am I not doing something correctly. 
Using Windows 10, Firefox and Chrome.
Thanks
![image](https://user-images.githubusercontent.com/63753756/79704207-2c9cc200-8265-11ea-81d7-4c810a5d91ab.png)

**Comment by riccardoklinger** [comment] 2020-04-20 02:28
Have you selected something? Can you share an example dataset?

Von meinem iPhone gesendet

**Comment by DLevasheff** [comment] 2020-04-20 04:10
In that screen shot I had not selected anything, but it didn't seem to matter.
I will attach a zip of the web page.
Thanks
[qgis2web_2020_04_14-12_26_57_363897.zip](https://github.com/tomchadwin/qgis2web/files/4501165/qgis2web_2020_04_14-12_26_57_363897.zip)

**Comment by sajonasra** [comment] 2020-05-11 15:48
I have come across the same problem with the string filters. "Clear filter" button does not work.
![grafik](https://user-images.githubusercontent.com/65179698/81579809-e55da900-93ac-11ea-8c04-8270d896e1a7.png)
also it seems the abstract does not show.

**Comment by edbusana** [comment] 2020-05-17 21:23
Clear Filter, only works if you select an option from your list. And the action of the command is not similar to clicking on something, it seems to do nothing, but watch if something changes (map, list).

**Comment by tomchadwin** [comment] 2020-06-05 14:08
I think this might be caused by the fact that raw layer names are being used for the filter widget id - from the top filter in the zipped example above, we have:

```javascript
sel_CommonName.id = "sel_Common Name";
```

Presumably this should be:

```javascript
sel_CommonName.id = "sel_CommonName";
```

I'll see if I can fix it.

**Comment by tomchadwin** [comment] 2020-06-05 14:30
OK, I can fix the Python side of it, but there's no client-side JS equivalent of the python `safeName()` function, so we need one. Are you able to take a look. @riccardoklinger?

**Comment by tomchadwin** [comment] 2020-06-05 14:45
I've committed a possible fix to master, but I don't have source data with which I can easily test. Can you test, @DLevasheff @sajonasra @edbusana @riccardoklinger, and report back?

**Comment by tomchadwin** [comment] 2020-06-15 09:31
Closing without feedback

**Closed by tomchadwin** 2020-06-15 09:31 UTC
Labels: Leaflet, bug

**Comment by sajonasra** [comment] 2020-06-30 09:43
Thanks @tomchadwin ! I checked the filtering and it works! Sorry for not checking faster! 
👍
