### ISSUE TITLE
Leaflet graduated/categorized layers in layers list don't all appear initially on map

### ISSUE THREAD

**Issue by michellemoine** [tomchadwin/qgis2web#190] opened 2016-01-31 15:59 UTC
Hi Tom,
I am using Qgis Lyon and have made a map with graduated style.
When exported to OL3, the map displays correctly eventhough when I click on any part of the map nothing happens.
If the same map is exported to Leaflet, nothing is displayed. I just get a blank page with no errors.

If the same map is exported with a single symbol style, everything works as expected.

Any help will be much appreciated
Mich

**Comment by lucacasagrande** [comment] 2016-01-31 18:45
I don't think it's currently supported.

**Comment by tomchadwin** [comment] 2016-01-31 19:10
It is supported. At the bottom of the Help tab, or on the home page here, there are instructions for debugging. Can you find the bit which directs you to javascript errors (F12 in the preview)? A blank map is normally the symptom of a javascript error.

**Comment by michellemoine** [comment] 2016-01-31 23:27
The error is:
Uncaught SyntaxError: More than one default clause in switch statement

And here is the part of JS:

   default:
                    return {
                    weight: '1.04',
                    fillColor: '#bd0026',
                    color: '#809848',
                    dashArray: '',
                    lineCap: 'butt',
                    lineJoin: 'miter',
                    opacity: '1.0',
                    fillOpacity: '1.0',
                };
                break;

Thanks for your help

**Comment by tomchadwin** [comment] 2016-01-31 23:50
OK. Look at your graduated styles in QGIS. Alongside the styles assigned to the different ranges, there will be two styles with no values associated. Delete one of those and try the export again.

**Comment by michellemoine** [comment] 2016-02-01 00:07
Thanks Tom. I am getting better results indeed. I am still experiencing wrong colors or missing colors and many other issues. I'll try to summarise all these issues better and will post back in the morning.

**Comment by tomchadwin** [comment] 2016-02-01 00:16
If you can also make your layer available, that will help.

**Comment by michellemoine** [comment] 2016-02-01 11:28
I've sorted out few problems due to file names or joined excel sheets column title with french special characters, which are not working well with leaflet but play nicely with OL3.
After that, Qgis seems to have few issues with categorised or graduated style if the numbers have too many decimals.

After correcting of all above issues, leaflet didn't complain anymore. See the results here:
http://bassinefe-liege.be/qgis2web
http://bassinefe-liege.be/qgis2web_graduated

The first link is a leaflet with Single Symbol. Works as expected
The second link is a leaflet with Graduated wich will only shows the other layers after they are checked out an in again. If the legend is unchecked before exporting, all layers are displayed correctly.

**Comment by tomchadwin** [comment] 2016-02-01 13:43
OK, I see the problem, but don't have an explanation. If you are able, can you test a couple of things for me?

- change the stacking order of your layers in QGIS and export again
- only export each of those three layers individually in turn

Each time, what I'd like to know is which layers are initially visible, and which not. In other words, I want to narrow down whether the behaviour is specific to a given layer or layers, or whether it depends on, eg, the stacking order or loading order of the layer.

**Comment by michellemoine** [comment] 2016-02-01 14:06
New layers order: http://bassinefe-liege.be/qgis2web_newlayersorder
Without layers list: http://bassinefe-liege.be/qgis2web_withoutlayerslist

**Comment by tomchadwin** [comment] 2016-02-01 14:08
Thanks, to conclude:

- the problem only occurs when the layers list is displayed
- it's related to layer order

I believe the issue might apply also to categorized layers, but not to single? Can anyone confirm?

**Comment by michellemoine** [comment] 2016-02-01 14:11
http://bassinefe-liege.be/qgis2web_layer1
http://bassinefe-liege.be/qgis2web_layer2
http://bassinefe-liege.be/qgis2web_layer3

**Comment by tomchadwin** [comment] 2016-02-01 14:12
OK, so it only occurs with multiple layers and layer list.

**Comment by michellemoine** [comment] 2016-02-01 14:23
There is another issue that seems to be related to the browser.
http://bassinefe-liege.be/qgis2web_graduated In IE11 I can access the information of the top layer (red circles) while I can also access the information of the second layer. The top layer stays on top as it should. In Chrome and in Firefox, the last layer is inaccessible without turning off all the other layers.

**Comment by michellemoine** [comment] 2016-02-01 14:43
The problem is caused by the Highlight Features. It works as it should without checking Highlight Features.

**Comment by tomchadwin** [comment] 2016-02-01 15:59
Sorry, are you talking about the problem of layers not being initially displayed, or this subsequent issue of accessing the information?

**Comment by michellemoine** [comment] 2016-02-01 16:11
It's not related to the display of the layers. The highlight features will interfere with the display of the top layer (Red dots).

**Comment by tomchadwin** [comment] 2016-02-01 16:19
Let me try to separate this out, as I am getting very confused.

**Comment by tomchadwin** [comment] 2016-02-01 16:20
Does this change in issue title accurately describe the first issue? Are you able to open a separate issue for the other problem?

**Comment by michellemoine** [comment] 2016-02-01 16:23
Ok, will do. Thank you

**Comment by tomchadwin** [comment] 2016-02-02 09:51
So, to return to the issue of layers not initially displaying on the map, is this as accurate a description of the issue as we can manage at the moment:

- more than one layer required
- at least one layer must be graduated (?or categorized)
- the layer list must be present

Anything incorrect with that? Anything missing?

**Comment by tomchadwin** [comment] 2016-02-02 12:00
JS error is `TypeError: 'undefined' is not an object (evaluating 'this._map._pathRoot')`

**Comment by tomchadwin** [comment] 2016-02-02 13:35
Confirmed that categorized layers also exhibit the problem, and that layer order determines which layer fails to display. Still not clear what the cause is.

**Comment by tomchadwin** [comment] 2016-02-02 14:27
I can't figure this one out. Can anyone else help?

**Comment by michellemoine** [comment] 2016-02-03 00:50
Changing the "Scale/Zoom" "Extent" option to "Canvas extent" instead of "Fit to layer extent" solved the problem.
http://bassinefe-liege.be/qgis2web_canvasextent

**Comment by tomchadwin** [comment] 2016-02-03 09:49
Confirmed. So, to reproduce this problem, the following is required:

- Leaflet format
- multiple layers
- at least one layer is graduated or categorized
- layers list is present
- "Fit to layers extent"

This is starting to remind me of a previous issue. Let me find the reference.

**Comment by tomchadwin** [comment] 2016-02-03 10:16
No, the other issue is not relevant - it related to basemaps.

**Comment by tomchadwin** [comment] 2016-02-03 10:18
If I add a fitBounds() with arbitrary values to the instantiation of L.map, all layers display correctly. However, it introduces an unwanted initial pan/zoom animation. Why would the absence of fitBounds() cause layers not to display?

**Comment by tomchadwin** [comment] 2016-02-03 10:46
OK, I might have fixed this in master. Can you test and let me know?

**Closed by tomchadwin** 2016-02-03 10:46 UTC
Labels: bug, help wanted, Leaflet, styles, vectors

**Comment by michellemoine** [comment] 2016-02-03 12:44
Ok, it's working fine now. Thank you

**Comment by tomchadwin** [comment] 2016-02-05 16:27
Released as 1.0.0-RC3 and pushed to QGIS plugins repo
